### ISSUE TITLE
[cinder-csi-plugin] CreateContainerError when arbitrary container mountPath contains double quotes

### ISSUE THREAD

**Issue by johannesfrey** [kubernetes/cloud-provider-openstack#1061]
/kind bug

**What happened**:

During an update of the [cinder-csi-nodeplugin DaemonSet](https://github.com/kubernetes/cloud-provider-openstack/blob/v1.17.0/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml) one Pod of the cinder-csi-nodeplugin could not be started again (`CreateContainerError`) because on that Node there was a Pod running as well that contained double quotes in its mountPath.

A `kubectl describe` revealed following:

```
  Warning  Failed     11s                kubelet, kube-node03  Error: failed to generate container "3a0bd914c862e613de04175150aaee6e645983bdbbc9f0f7ecce6af5e4060d20" spec: parsing '/kubelet/pods/a236ebe7-40b7-48b5-8458-ff1321d0ee67/volumes/kubernetes.io~configmap/content/"bar"' failed: unable to unquote root field: invalid syntax
```

The above error comes directly from containerd in my case. See: https://github.com/containerd/containerd/blob/v1.3.4/mount/mountinfo_linux.go#L90

From a Kubernetes validation point of view using double quotes seems to be allowed, as the resource that uses it can be created without any problems. The cinder-csi-nodeplugin pod on that Node can only be started again when the Pod that references the double quote mount is being deleted.

**What you expected to happen**:

That the cinder-csi-nodeplugin handles this error more gracefully. 

**How to reproduce it**:

* Have the cinder-csi-nodeplugin DaemonSet running
* Deploy follwing test resources:
  ```yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: content
  data:
    test: |-
      foo
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: busybox
    labels:
      app: busybox
  spec:
    containers:
    - image: busybox
      command:
        - /bin/sh
        - -c
        - "tail -f /dev/null"
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
      - name: content
        mountPath: /tmp
      - name: content
        mountPath: '/tmp/"bar"'
        subPath: '"bar"'
    restartPolicy: Always
    volumes:
    - name: content
      configMap:
        name: content
  ```
* Delete the cinder-csi-nodeplugin Pod on the Node where the above Pod has been started
* After deletion the cinder-csi-nodeplugin tries to start again but remains in `CreateContainerError` state with the `unquote` error event mentioned above

**Anything else we need to know?**:

The cinder-csi-nodeplugin Pods is not affected while it is running when a resource is deployed with a double quote in its mountPath. Only when the cinder-csi-nodeplugin Pod is being deleted/updated the error appears.
The issue was observed in version v1.17.0 but could also be reproduced on version v.1.16.0.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.17.0

**Comment by jichenjc** [comment]
is this a cinder CSI issue ? looks like this is general yaml parse issue?
not sure whether it's in the scope

**Comment by johannesfrey** [comment]
> is this a cinder CSI issue ? looks like this is general yaml parse issue?
> not sure whether it's in the scope

Yeah I also was not totally sure where to address this... Decided to put it here as it seems that "only" the csi cinder plugin seems to have a problem with this.
As mentioned above, creating a Pod works fine and inside the container you can actually see the mount with double quotes (so the container creation via Kubernetes -> container runtime works). So either the double quote is actually a valid character in a directoy name (at least under Linux?!) or Kubernetes does not throw an error where it normally should?!

**Comment by jichenjc** [comment]
`vi "abc"` is same to `vi abc` in linux :)
but really don't know why you have such issue ...

**Comment by johannesfrey** [comment]
> `vi "abc"` is same to `vi abc` in linux :)
> but really don't know why you have such issue ...

This also works on Linux :wink::
* `vi '"abc"'`
* `mkdir "'def"'`

We are managing Kubernetes clusters and one update broke (cinder-csi-nodeplugin could not be started again) because a user was using double quotes as mountpath via helm template variable subsititution.
Nevertheless, so do you mean the cinder-csi-plugin works as intended here? If so, were should the validation happen that prohibits the use of double quotes. Because a non starting nodeplugin kind of a "hard" way to communicate that this is not allowed :).

**Comment by jichenjc** [comment]
to my understanding  this is really not something should be handle by CSI cinder.. maybe other folks will have more input
```
  - name: content
      mountPath: '/tmp/"bar"'
      subPath: '"bar"'
```

I will check whether CSI cinder mount code has anything to it ... thanks

**Comment by johannesfrey** [comment]
> to my understanding this is really not something should be handle by CSI cinder.. maybe other folks will have more input
> 
> ```
>   - name: content
>       mountPath: '/tmp/"bar"'
>       subPath: '"bar"'
> ```
> 
> I will check whether CSI cinder mount code has anything to it ... thanks

Sure, thank you!
I think the cause for this is that the nodeplugin uses the path to the kubelet pods directory as volumeMount:

```yaml
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: pods-mount-dir
```

So you are absolutely right, it looks as this really is not a problem of CSI per se (every container that would try mount the pods mount dir would fail in this way) but rather with containerd not being able to handle double quotes in mount paths.
Please feel free to close this issue if you also agree with my sentiment :).
