### ISSUE TITLE
Add ability to configure loadbalancer member subnet id

### ISSUE THREAD

**Issue by bartjkdp** [kubernetes/cloud-provider-openstack#1086]
We would like to create a load balancer in an external subnet but refers to members in an internal subnet. We are using this to enable external IPv6 support. Currently this is not possible as the cloud provider always uses `lbaas.opts.SubnetID` for creating the members:

https://github.com/kubernetes/cloud-provider-openstack/blob/2493d936afe901a63066e4506dcfa716f1d96dc9/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L1110-L1117

Maybe we can introduce a new annotation for configuring the member subnet ID (e.g. `loadbalancer.openstack.org/member-subnet-id`)?

**Comment by bartjkdp** [comment]
Created a Draft PR for this.

**Comment by lingxiankong** [comment]
Is it possible that defining LoadBalancerClass in the config file according to https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/expose-applications-using-loadbalancer-type-service.md#switching-between-floating-subnets-by-using-preconfigured-classes and customized the VIP network/subnet of the load balancer, then use `lbaas.opts.SubnetID` as the member subnet?

**Comment by bartjkdp** [comment]
@lingxiankong thanks for your answer! It is possible to define multiple loadbalancer classes, but as far as I can see it is not possible to configure different subnet id's for the members and the loadbalancer itself.

**Comment by lingxiankong** [comment]
@bartjkdp let me clarify again, the members will use `lbaas.opts.SubnetID`, and the loadbalancer will use subnet-id configured in LoadBalancerClass.

**Comment by lingxiankong** [comment]
@bartjkdp Have you tested my proposed suggestion?

**Comment by bartjkdp** [comment]
@lingxiankong sorry, a bit busy. I will have a look this week and let you know!

**Comment by bartjkdp** [comment]
Thanks @lingxiankong for your suggestions, this solves my problem. The configuration creates a loadbalancer in *{external-subnet-id}* with members in *{internal-subnet-id}*:

**cloud.config**
```
[LoadBalancerClass "ipv6"]
subnet-id="{external-subnet-id}"
```

**service.yaml**
```
kind: Service
apiVersion: v1
metadata:
  name: test
  namespace: default
  annotations:
    loadbalancer.openstack.org/class: "ipv6"
    loadbalancer.openstack.org/subnet-id: "{internal-subnet-id}"
    service.beta.kubernetes.io/load-balancer-source-ranges: "::/0"
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
  selector:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: test
  type: LoadBalancer
  externalTrafficPolicy: Cluster

  type: LoadBalancer
  externalTrafficPolicy: Cluster
```
