### ISSUE TITLE
[cinder-csi-plugin][docs] Disaster recovery instruction is missing

### ISSUE THREAD

**Issue by eumel8** [kubernetes/cloud-provider-openstack#1141]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

I try to figure out a disaster recovery concept for Cinder volumes which were previosly attached as PVC on a burn cluster. Imagine the cluster is destroyed (for whatever reasons), the volumes are still in the OpenStack backend present and I know the name/id

**What you expected to happen**:

After create a new cluster I should be able to recover PVCs:

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-ssd-test
  namespace: demoapp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: sata
  volumeMode: Filesystem
  volumeName: pvc-36b6d348-7eb0-4be9-a324-5315b22dbc04
```
Verified, the volume is in state available in backend.
After apply and try to mount on a Pod the PVC status is Pending.

I tried to set some annotations, like

```
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
    volume.kubernetes.io/selected-node: vm-k8s-01-ranchernode-3
```
but this gives only PVS status "Lost" and the error message on the attacher:

I0729 09:53:20.468006       1 csi_handler.go:219] Error processing "csi-ssd-test": failed to attach: persistentvolume "pvc-36b6d348-7eb0-4be9-a324-5315b22dbc04" not found

Of course, the volume should be attached to the node, but this makes no difference

**Anything else we need to know?**:

My expectation would be, the csi-attacher is able to connect the volume from the node on the new cluster without copy the data on the node level. Maybe I have overseen the trick.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.18
- OpenStack version: unknown
- Others: Ubuntu 18.04 host system

**Comment by jichenjc** [comment]
this seems a valid use case but don't know this is a doc only issue or need some code change..

**Comment by ramineni** [comment]
@eumel8 You need to manually create PV also along with pvc? Have you tried it

**Comment by eumel8** [comment]
@ramineni yeah, it works!

```
$ openstack volume show e129824a-16fa-486d-a8c7-482945a626ff
+--------------------------------+-----------------------------------------------------------------+
| Field                          | Value                                                           |
+--------------------------------+-----------------------------------------------------------------+
| attachments                    | []                                                              |
| availability_zone              | eu-de-01                                                        |
| bootable                       | false                                                           |
| consistencygroup_id            | None                                                            |
| created_at                     | 2020-11-30T15:16:23.788791                                      |
| description                    | Created by OpenStack Cinder CSI driver                          |
| encrypted                      | False                                                           |
| id                             | e129824a-16fa-486d-a8c7-482945a626ff                            |
| multiattach                    | True                                                            |
| name                           | pvc-ba482e24-2e76-48fd-9be5-504724922185                        |
| os-vol-host-attr:host          | pod07.eu-de-01#SATA                                             |
| os-vol-mig-status-attr:migstat | None                                                            |
| os-vol-mig-status-attr:name_id | None                                                            |
| os-vol-tenant-attr:tenant_id   | 7c3ec0b3db5f476990043258670caf82                                |
| properties                     | cinder.csi.openstack.org/cluster='kubernetes', readonly='False' |
| replication_status             | disabled                                                        |
| shareable                      | True                                                            |
| size                           | 9                                                               |
| snapshot_id                    | None                                                            |
| source_volid                   | None                                                            |
| status                         | available                                                       |
| storage_cluster_id             | None                                                            |
| type                           | SATA                                                            |
| updated_at                     | 2020-12-06T22:51:30.032404                                      |
| user_id                        | 2497435010e14245843bfe20e6f05024                                |
| volume_image_metadata          | {}                                                              |
+--------------------------------+-----------------------------------------------------------------+
```

cat recover-pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cinder.csi.openstack.org
  name: pvc-ba482e24-2e76-48fd-9be5-504724922185
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 9Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sib
    namespace: sib
  csi:
    driver: cinder.csi.openstack.org
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1606744152466-8081-cinder.csi.openstack.org
    volumeHandle: e129824a-16fa-486d-a8c7-482945a626ff
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.cinder.csi.openstack.org/zone
          operator: In
          values:
          - eu-de-01
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sata
  volumeMode: Filesystem
```

cat recover-pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
  name: sib
  namespace: sib
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sata
  volumeMode: Filesystem
```

* remove/crash pvc/pc from the dirty cluster
* check if volume is available in OpenStack
* re-attach pv+pvc to a new cluster
* check available data

Great! I think that's worth to mention as recover strategy in docs.
