### ISSUE TITLE
[occm] updating connection-limit annotation not working for Neutron

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes/cloud-provider-openstack#1147]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
If Neutron is used for LBaaS, a change to the service annotation `loadbalancer.openstack.org/connection-limit` is not picked up by the openstack-cloud-controller-manager.
Only if Octavia is used, a change is propagated to the OpenStack loadbalancer listener.

**What you expected to happen**:
Changing `loadbalancer.openstack.org/connection-limit` service annotation should be supported by Neutron and Octavia.

**How to reproduce it**:
Add the service annotation `loadbalancer.openstack.org/connection-limit` to an existing service of type `LoadBalancer` when using Neutron LBaaS.
```yaml
apiVersion: v1
kind: Service
metadata:
   name: test-service
   annotations:
     loadbalancer.openstack.org/connection-limit: "120"
spec:
   ports:
   - port: 22000
     protocol: TCP
     targetPort: 8080
   type: LoadBalancer
```

**Anything else we need to know?**:
This probably occurred as a side effect of [PR#837](https://github.com/kubernetes/cloud-provider-openstack/pull/837)

**Environment**:
- openstack-cloud-controller-manager version: master
- Openstack version: Vanilla (not Octavia)

<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
