### ISSUE TITLE
[occm] loadbalancer not updating when Octavia specific service annotations change

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes/cloud-provider-openstack#1149]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
A change to any of the service annotations
* `loadbalancer.openstack.org/timeout-client-data`
* `loadbalancer.openstack.org/timeout-member-connect`
* `loadbalancer.openstack.org/timeout-member-data`
* `loadbalancer.openstack.org/timeout-tcp-inspect`
* `loadbalancer.openstack.org/x-forwarded-for`

is not picked up by the openstack-cloud-controller-manager. Changes are only propagated to the OpenStack loadbalancer listener when it is initially created.

**What you expected to happen**:
Changing one of the above service annotations should be supported and the listener updated accordingly.

**How to reproduce it**:
Add the service annotation to an existing service of type `LoadBalancer`.
```yaml
apiVersion: v1
kind: Service
metadata:
   name: test-service
   annotations:
     loadbalancer.openstack.org/timeout-client-data: "100"
     loadbalancer.openstack.org/timeout-member-connect: "100"
     loadbalancer.openstack.org/timeout-member-data: "100"
     loadbalancer.openstack.org/timeout-tcp-inspect: "100"
     loadbalancer.openstack.org/x-forwarded-for: "true"
spec:
   ports:
   - port: 22000
     protocol: TCP
     targetPort: 8080
   type: LoadBalancer
```

**Anything else we need to know?**:
The same applies for the annotation `loadbalancer.openstack.org/proxy-protocol` but updating the loadbalancer pool protocol is not supported by Octavia.
See the Octavia API pool documentation [Update a pool detail](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=update-a-pool-detail#update-a-pool).
For updating the protocol, the pool has to be deleted and recreated keeping the following in mind:
* keep the floating ip
* keep the loadbalancer and listener (if possible)
* re-create the pool (and all others we may need to recreate)

**Environment**:
- openstack-cloud-controller-manager version: master
- Openstack version: Octavia

<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
