### ISSUE TITLE
[occm] bad loadbalancer listeners configuration with x-forwarded-for annotation

### ISSUE THREAD

**Issue by JrCs** [kubernetes/cloud-provider-openstack#1152]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
If a service of type LoadBalancer is create with the  `loadbalancer.openstack.org/x-forwarded-for: "true"` annotation all the listeners will be assign the HTTP protocol which cannot work with service types other than HTTP (like HTTPS).

**What you expected to happen**:
Only listener that "forward" HTTP protocol must have the HTTP protocol set.

**How to reproduce it**:
Create a service with the `loadbalancer.openstack.org/x-forwarded-for: "true"` annotation with 2 ports (so 2 listeners will be created).
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.openstack.org/x-forwarded-for: "true"
  labels:
    app: nginx-ingress
  name: nginx-ingress-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx-ingress
  type: LoadBalancer
```
This will create 2 listeners with protocol HTTP, and the service with port 443 (https) will not be accessible.

**Anything else we need to know?**:
DigitalOcean cloud provider have annotations to specify which port use which protocols: https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/annotations.md#servicebetakubernetesiodo-loadbalancer-http-ports

**Environment**:
- openstack-cloud-controller-manager version: 1.18.0
