### ISSUE TITLE
[occm] LB Pool not updated when proxy-protocol service annotation changed

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes/cloud-provider-openstack#1167]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
A change to the service annotation
* `loadbalancer.openstack.org/proxy-protocol`

is not picked up by the openstack-cloud-controller-manager. Changes are only propagated to the OpenStack loadbalancer pool when it is initially created.

**What you expected to happen**:
Changing the above service annotation should be supported and the pool updated/recreated accordingly.

**How to reproduce it**:
Add the service annotation to an existing service of type `LoadBalancer`.
```yaml
apiVersion: v1
kind: Service
metadata:
   name: test-service
   annotations:
     loadbalancer.openstack.org/proxy-protocol: "true"
spec:
   ports:
   - port: 22000
     protocol: TCP
     targetPort: 8080
   type: LoadBalancer
```

**Anything else we need to know?**:
Updating the loadbalancer pool protocol is not supported by Octavia.
See the Octavia API pool documentation [Update a pool detail](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=update-a-pool-detail#update-a-pool).
For updating the protocol, the pool has to be deleted and recreated keeping the following in mind:
* keep the floating ip
* keep the loadbalancer and listener (if possible)
* re-create the pool (and all others we may need to recreate)

This issue is a follow up from #1149.

**Environment**:
- openstack-cloud-controller-manager version: master
- Openstack version: Octavia

<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
