### ISSUE TITLE
Filter main ip address(es)

### ISSUE THREAD

**Issue by kartoch** [kubernetes/cloud-provider-openstack#118]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

Goal: have a way to configure Openstack cloud provider to use a specific address for each node.

More precisely, following kubernetes/kubernetes#62163 and kubernetes/cloud-provider-openstack#89, it is now possible to disable IPv6 addresses. But what if a node has two (or more) IPv4 and/or IPv6 addresses ? For instance let's have the following configuration:

```
  status:
    addresses:
    - address: 10.1.0.45
      type: InternalIP
    - address: 2001:41d0:302:1100::a:1720
      type: InternalIP
    - address: 54.38.91.250
      type: InternalIP
    - address: k8s-worker-1
      type: Hostname
```

The order of addresses is based on comparison between the address string values. So the first one (10.1.0.45) is ideally the main address used by kubernetes.

But it is more problematic for the following ones:

```
  status:
    addresses:
    - address: 15.13.37.45
      type: InternalIP
    - address: 192.168.27.34
      type: InternalIP
    - address: k8s-worker-1
      type: Hostname
```

Even if there is no IPv6 address, the public address is used as the kubernetes main address, which is something not really secure, especially if there is a private network.

**What you expected to happen**:

Openstack cloud provider must be provide a way to force that a specific address is the main address.

**Comment by yanndegat** [comment]
hi @kartoch 

this could easily be done by filtering addresses on a specific subnet cidr that could be defined 
in the networking opts

@dims could this be relevant ? if so i can try to make a PR

**Comment by kartoch** [comment]
hi @yanndegat,

Reading your comment, it makes me wonder why there is several addresses in `addresses` entry. The addresses available in this entry are the ones used by kubernetes for internal exchange (mainly master <-> kubelets) so is there an interest to enter several addresses here  ? 

I can see at least one interest : IPv4/IPv6 dual support. If several several IPv4 AND IpV6 addresses, that would mean selecting a subset of the IPv4/IPv6 addresses, so the networking option must be able to accept several filters.

@dims is that (also) relevant ?

**Comment by dims** [comment]
cc @anguslees 
cc @FengyunPan2 

folks, thoughts pleas

**Comment by zetaab** [comment]
How 54.38.91.250 is internalip in example?

Example of one our node addresses:
```
Addresses:
  InternalIP:	192.168.0.196
  InternalIP:	192.168.0.218
  InternalIP:	192.168.0.222
  InternalIP:	192.168.0.226
  InternalIP:	192.168.0.230
  ExternalIP:	10.222.132.11
  ExternalIP:	10.222.132.13
  ExternalIP:	10.222.132.15
  Hostname:	dc1-egress-1-1
```

Imo if 54.38.91.250 is marked as internalip in openstack, its not correct

**Comment by kartoch** [comment]
@zetaab thank you for your feedbacks. It seems you have an 'ExternalIp` and `InternalIp` in your example. In my case after openstack configuration my addresses fields are all `InternalI`:

```
  status:
    addresses:
    - address: 10.1.0.45
      type: InternalIP
    - address: 2001:41d0:302:1100::a:1720
      type: InternalIP
    - address: 54.38.91.250
      type: InternalIP
    - address: k8s-worker-1
      type: Hostname
```

So it maybe a problem with the way I configure networks and/or how my provider connect to them. I am going to look at it.
