### ISSUE TITLE
[cinder-csi-plugin] Unable to attach or mount volumes: timed out waiting for the condition

### ISSUE THREAD

**Issue by alanbchristie** [kubernetes/cloud-provider-openstack#1206]
/kind bug

**What happened**:
Provisioner installed in our Kubernetes `v1.17.5` cluster. The provisioner is able to create and attach PVCs to the required node but Pods using the PVCs enter a **waiting** state with the error **Unable to attach or mount volumes: unmounted volumes=[data-volume], unattached volumes=[default-token-4w5lf data-volume]: timed out waiting for the condition**

* When the PVC is created a volume is created in OpenStack.
* When the Pod is created the OpenStack volume is attached to the corresponding node.

How can I determine what **Condition** the Pod's waiting for, and what might be happening?

**What you expected to happen**:
Provisioner creates volumes, attached them to the compute instance and Pod successfully mounts the volume.

**How to reproduce it**:
Using a simple PVC and Pod: -

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
  namespace: im-cinder-provisioner
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-cinder-sc-delete
  resources:
    requests:
      storage: '7Gi'
```

```
---
kind: Pod
apiVersion: v1
metadata:
  name: pysimple
  namespace: im-cinder-provisioner
spec:
  containers:
  - name: pysimple
    image: pysimple:2019.8
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: test
```

I suspect it's a setup problem in our cluster but I don't know where to look for debug or diagnostic information. What Pod logs should I inspect?

**Anything else we need to know?**:
1. I couldn't install the CSIDriver using `apiVersion: storage.k8s.io/v1` and instead had to use `apiVersion: storage.k8s.io/v1beta1`

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: `cinder-csi-1.1.2`
- OpenStack version: `Train`
- Others: `Kubernetes v1.17.5`
