### ISSUE TITLE
[cinder-csi-plugin] Does controllerplugin-rbac.yaml RoleBinding need a namespace?

### ISSUE THREAD

**Issue by alanbchristie** [kubernetes/cloud-provider-openstack#1215]
/kind bug

**What happened**:
Getting kubernetes error when deploying the `csi-resizer-role-cfg` **RoleBinding**, asking for a `namespace`. The current definition is: -

```
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role-cfg
subjects:
  - kind: ServiceAccount
    name: csi-cinder-controller-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: external-resizer-cfg
  apiGroup: rbac.authorization.k8s.io
```

As it's not a cluster object should't its metadata contain a namespace, i.e....

```
metadata:
  name: csi-resizer-role-cfg
  namespace: {{ .Release.Namespace }}
```

**What you expected to happen**:
Deploy the `csi-resizer-role-cfg` **RoleBinding** without an error.

**How to reproduce it**:
Deploy the template.

**Anything else we need to know?**:
No

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: n/a
- OpenStack version: n/a
- Others:
