### ISSUE TITLE
Running Kubernetes IPv6 CI tests on OpenStack cloud

### ISSUE THREAD

**Issue by dims** [kubernetes/cloud-provider-openstack#122]
Based one from @leblancd 

Let's start with the conformance test suite and see what it would take to enable IPv6 based job
- We need to check if vexxhost can support IPv6 in the VM(s) we use 
   * seems like a possibility looking at http://logs.openlabtesting.org/logs/19/119/4800ccab78624506960c42559b61a48a7360c473/cloud-provider-openstack-acceptance-test-e2e-conformance/cloud-provider-openstack-acceptance-test-e2e-conformance/8c6cbbd/zuul-info/zuul-info.ubuntu-xenial-vexxhost.txt
- If we can't use t, we will have to use devstack VM (and enable kuryr?)
- Next, they use kubeadm with following config, we have to translate this to local-up-cluster (need to check if images built from master is good enough too)
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: 1.10.0
api:
  advertiseAddress: fd00::100
networking:
  serviceSubnet: fd00:1234::/110
unifiedControlPlaneImage: diverdane/hyperkube-amd64:v1.9.0-beta.0.ipv6.2
tokenTTL: 0s
nodeName: kube-master
```
- After that they use the following snippet to run tests:
```
export KUBECONFIG=/home/openstack/.kube/config
export KUBE_MASTER=local
export KUBE_MASTER_IP="[fd00:1234::1]:443"
export KUBERNETES_CONFORMANCE_TEST=n
cd $GOPATH/src/k8s.io/kubernetes
go run hack/e2e.go -- --provider=local --v --test --test_args="--host=https://[fd00:1234::1]:443 --ginkgo.focus=Networking|Services --ginkgo.skip=IPv4|Networking-Performance|Federation|preserve\ssource\spod|session\saffinity:\sudp|functioning\sNodePort --num-nodes=2"
```
