### ISSUE TITLE
[octavia-ingress-controller] Doesn't publish the full certificate chain

### ISSUE THREAD

**Issue by dr4Ke** [kubernetes/cloud-provider-openstack#1220]
**Is this a BUG REPORT or FEATURE REQUEST?**:

To me, this is a bug. But it could also be viewed as a feature request.

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The ingress controller created a `TERMINATED_HTTPS` load balancer using a provided TLS secret. The LB is responding to requests presenting only the leaf certificate, not the chain.

**What you expected to happen**:
The LB should present the leaf certificate **and** any intermediate certificates needed (fullchain)

**How to reproduce it**:
- Create a TLS secret in kubernetes, with the full chain in `tls.crt`
```
kubectl create secret tls my-cert --cert cert.pem --key key.pem
```
- Create an octavia ingress
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
     kubernetes.io/ingress.class: openstack
  name: nginx
spec:
  rules:
  - host: host.domain.com
    http:
      paths:
      - backend:
          serviceName: nginx-http
          servicePort: 80
  tls:
  - hosts:
    - host.domain.com
    secretName: my-cert
EOF
```
- Inspect the presented certificates:
```
openssl s_client -connect host.domain.com:443
[...]
---
Certificate chain
 0 s:CN = host.domain.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
---
```

A manually configured barbican TLS secret, with full chain show something like:
```
---
Certificate chain
 0 s:CN = host.domain.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.19.0
- OpenStack version: Train
- Others:
