### ISSUE TITLE
[occm] LB conflict with multiple clusters

### ISSUE THREAD

**Issue by dr4Ke** [kubernetes/cloud-provider-openstack#1273]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

We deployed 2 clusters in the same openstack project. In both, we deployed the same application within the same namespace. It resulted with only one LB creation, both controllers considering it is theirs. Moreover, when removing one of these applications, the LB was removed too.

**What you expected to happen**:

2 LB should be deployed. The controller should be able to distinguish its own resources. Maybe using the service or namespace UID in the LB name. For example `kube_service_{{ NAMESPACE_NAME }}_{{ NAMESPACE_UID }}_{{ SERVICE_NAME }}`

**How to reproduce it**:

- install 2 kubernetes clusters
- create a `app1` namespace in both
- deploy a loadbalancer service in this namespace on both clusters, such as:
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: test-lb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: LoadBalancer
```
- see only one LB named `kube_service_kubernetes_default_test-lb`
- remove one service
- see the LB removed

**Anything else we need to know?**:

I don't think so.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v.1.19.0
- OpenStack version: Train
- Others:
