### ISSUE TITLE
[occm] insert_headers always in Update Listener body

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes/cloud-provider-openstack#1294]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When the CCM updates an existing listener, the `insert_header` is always part of the JSON body send to the OpenStack API, even if there is no change for `keepClientIP` or `loadbalancer.openstack.org/x-forwarded-for` annotation.

**What you expected to happen**:
Would expect to only have updated fields in the body of the Listener Update request.
E.g. when updating ` loadbalancer.openstack.org/timeout-member-data: "49998"`, the body should look like this:
`{"timeout_member_data":49998}`

**How to reproduce it**:
Create a service of type `LoadBalancer`. After the service is reconciled, add an annotation e.g. `loadbalancer.openstack.org/timeout-member-data: "49998"`. Set a breakpoint in [`gophercloud/openstack/loadbalancer/v2/listeners/requests.go line 237`](https://github.com/gophercloud/gophercloud/blob/0e6f9ce41455b967839ac9ce6ecf61eaa8d9b283/openstack/loadbalancer/v2/listeners/requests.go#L237) and check the content of the variable `b`.

The request body will look like this:
`{"timeout_member_data":49998,"insert_headers":{}}`

*`service.yaml`*
```yaml
apiVersion: v1
 kind: Service
 metadata:
   annotations:
     loadbalancer.openstack.org/timeout-member-data: "49998"
   name: service1
 spec:
   ports:
     - name: https
       port: 443
       protocol: TCP
       targetPort: 8443
   type: LoadBalancer
```
k apply -f service.yaml

**Anything else we need to know?**:
The value of `InsertHeaders` in `listeners.UpdateOpts{}` at https://github.com/kubernetes/cloud-provider-openstack/blob/90378cf639cd8bab721bead7e1d5f896b8b768c0/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L1737 is not `nil`. I assume, that only if a value is `nil`, the `json.marshal` will ignore the field.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.19
- OpenStack version: Octavia

<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
