### ISSUE TITLE
[cinder-csi-plugin] IgnoreVolumeAZ does not work for volumes with Topology

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#1300]
**Is this a BUG REPORT or FEATURE REQUEST?**: bug

 /kind bug

**What happened**:  I am testing this new topology thing in two different openstack. In one openstack I have setup where I have 3 compute azs (zone-1, zone-2, zone-3) and 1 volume az (nova). I should be able to use IgnorevolumeAZ option (https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L152) somehow. However, when topology is enabled using featureflag (in next version it will be enabled for ALL so this will break things for everybody who is using ignorevolumeaz) the nova zone for volumes cannot be used. 

**What you expected to happen**: I expect that I could still use csi provider after topology feature.

**How to reproduce it**: 

1) OpenStack region with zone names that does not match between compute and volume, you have that if you have been using ignorevolumeaz option.
2) enable topology featureflag for provisioner (and use like 2.0.3 version)
3) use storageclass

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: csi-sc-cinderplugin
parameters:
  availability: nova
  type: solidfire
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
4) try to create volume

I have loglevel 4 in cinder-csi-plugin and the result is this:

```
I1030 15:05:39.988102       1 controllerserver.go:44] CreateVolume: called with args {Name:pvc-6084d54f-c2d9-43af-b7af-2ac62f8bd33d CapacityRange:required_bytes:17179869184  VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[availability:nova type:solidfire] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:requisite:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"zone-2" > > requisite:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"zone-3" > > requisite:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"zone-1" > > preferred:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"zone-1" > > preferred:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"zone-2" > > preferred:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"zone-3" > >  XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

The problem is here https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L68-L76 because, now the topologies has even some data. The availability parameter is just ignored. It should not be ignored if we have ignoreaz use-case.
