### ISSUE TITLE
Failed node "shutdown" / volume re-attachment 

### ISSUE THREAD

**Issue by elgamal2020** [kubernetes/cloud-provider-openstack#1354]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

We have a problem that need your support for 

Currently when the node where the pod is scheduled is shutdown “simulation of unexpected outage” the volume remains attached to it and cant get the pod scheduled to another node 

Note: it works for node draining 

To reproduce 
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: busybox
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
         - sleep
         - "36000"
        volumeMounts:
        - mountPath: "/data"
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: busybox-data

kubectl get nodes
NAME      STATUS   ROLES    AGE   VERSION
clus1     Ready    master   34d   v1.19.3
clus2     Ready    master   34d   v1.19.3
clus3     Ready    master   34d   v1.19.3
worker1   Ready    <none>   29d   v1.19.3

```
 ```

kubectl apply -f deployment-busybox.yaml
deployment.apps/busybox-deployment created
```
```


kubectl get pods -o wide
NAME                                        READY   STATUS    RESTARTS   AGE   IP              NODE      NOMINATED NODE   READINESS GATES
busybox-deployment-68f5856d87-xjzmp         1/1     Running   0          23s   10.233.111.21   worker1   <none>           <none>

 
```

Then powering off the instance 

kubectl get pods -o wide
NAME                                        READY   STATUS              RESTARTS   AGE     IP              NODE      NOMINATED NODE   READINESS GATES
busybox-deployment-68f5856d87-jnk5h         0/1     ContainerCreating   0          2m43s   <none>          clus1     <none>           <none>
busybox-deployment-68f5856d87-xjzmp         1/1     Terminating         0          13m     10.233.111.21   worker1   <none>           <

```
kubectl describe pod busybox-deployment-68f5856d87-jnk5h
Name:           busybox-deployment-68f5856d87-jnk5h
Namespace:      default
Priority:       0
Node:           clus1/10.10.10.125
Start Time:     Mon, 21 Dec 2020 23:01:36 +0000
Labels:         app=busybox
                pod-template-hash=68f5856d87
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/busybox-deployment-68f5856d87
Containers:
  busybox:
    Container ID:
    Image:         busybox
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
      36000
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gd4cc (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  busybox-data
    ReadOnly:   false
  default-token-gd4cc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gd4cc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Normal   Scheduled           13m                    default-scheduler        Successfully assigned default/busybox-deployment-68f5856d87-jnk5h to clus1
  Warning  FailedAttachVolume  13m                    attachdetach-controller  Multi-Attach error for volume "pvc-f097e698-506d-4e20-8e16-634f591c48b1" Volume is already used by pod(s) busybox-deployment-68f5856d87-xjzmp
  **Warning  FailedMount         2m36s (x2 over 4m52s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-gd4cc data]: timed out waiting for the condition
  Warning  FailedMount         19s (x4 over 11m)      kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data default-token-gd4cc]: timed out waiting for the condition**

```
 

 

**What you expected to happen**:

**How to reproduce it**:

explained 
**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:
