### ISSUE TITLE
[octavia-ingress-controller] Existing pools are rebuilt when updating Ingress

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#1417]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When I update an existing Ingress, I noticed that all the existing pools are rebuilt even the change doesn’t impact the existing pools.

This update takes up to minutes, which means an production system will have service outage when adding new pool on ingress.

**What you expected to happen**:
When updating Ingress host name or path, the existing pools shouldn't be rebuilt, because the backend service doesn't change.

**How to reproduce it**:
1. Create an Ingress

    ```
    cat <<EOF | kubectl apply -f -
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: test-octavia-ingress
      annotations:
        kubernetes.io/ingress.class: "openstack"
        octavia.ingress.kubernetes.io/internal: "true"
    spec:
      defaultBackend:
        service:
          name: nginx
          port:
            number: 80
      rules:
        - host: test.com
          http:
            paths:
            - path: /hostname
              pathType: Exact
              backend:
                service:
                  name: hostname
                  port:
                    number: 8080
    EOF
    ```

1. Update path of the Ingress

    ```
    cat <<EOF | kubectl apply -f -
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: test-octavia-ingress
      annotations:
        kubernetes.io/ingress.class: "openstack"
        octavia.ingress.kubernetes.io/internal: "true"
    spec:
      defaultBackend:
        service:
          name: nginx
          port:
            number: 80
      rules:
        - host: test.com
          http:
            paths:
            - path: /ping                      <======= change here.
              pathType: Exact
              backend:
                service:
                  name: hostname
                  port:
                    number: 8080
    EOF
    ```

In openstack, the lb pools are recreated.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:
