### ISSUE TITLE
[cinder-csi-plugin] Openstack credential info exposed when specifying secret in storageclass

### ISSUE THREAD

**Issue by Fedosin** [kubernetes/cloud-provider-openstack#1469]
When setting the TraceAll loglevel for Cinder CSI Driver and specifying secret in storageclass, the OpenStack credential info is exposed from the log.

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

We can get the credential info from the related logs: 
```sh
$ kubectl -n openshift-cluster-csi-drivers logs openstack-cinder-csi-driver-controller-78d9f84b7d-d7xmq -c csi-driver

I0402 09:31:13.903967       1 utils.go:81] GRPC request: name:"pvc-62646783-60a6-48eb-911e-698e521887d3" capacity_range:<required_bytes:2147483648 > volume_capabilities:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > secrets:<key:"clouds.yaml" value:"clouds:\n  openstack:\n    auth:\n      auth_url: https:///REDACTED/.redhat.com:13000/v3\n      password: eex/REDACTED/eg9ke\n      project_id: 542c6ebd48bf40fa857fc245c7572e30\n      project_name: openshift-qe-jenkins\n      user_domain_name: redhat.com\n      username: psi-/REDACTED/-jenkins\n    endpoint_type: public\n    identity_api_version: \"3\"\n    region_name: regionOne\n    verify: true\n" > accessibility_requirements:<requisite:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"nova" > > preferred:<segments:<key:"topology.cinder.csi.openstack.org/zone" value:"nova" > > >
I0402 09:31:13.904076       1 controllerserver.go:44] CreateVolume: called with args {Name:pvc-62646783-60a6-48eb-911e-698e521887d3 CapacityRange:required_bytes:2147483648  VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[] Secrets:map[clouds.yaml:clouds:
  openstack:
    auth:
      auth_url: https:///REDACTED/.redhat.com:13000/v3
      password: eex/REDACTED/9ke
      project_id: 542c6ebd48bf40fa857fc245c7572e30
      project_name: openshift-qe-jenkins
      user_domain_name: redhat.com
      username: psi-/REDACTED/-jenkins
    endpoint_type: public
    identity_api_version: "3"
    region_name: regionOne
    verify: true
```
**What you expected to happen**:

We should not get the credential info from the related logs.

**How to reproduce it**:
1. Install Cinder CSI Driver.
2. Set the Cinder CSI Driver loglevel to TraceAll
3. Create new storage with Cinder CSI Driver and specify secret like provisioner secret in storageclass
$ more /tmp/sc.yaml 
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-secret-csi
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/provisioner-secret-name: openstack-cloud-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-cluster-csi-drivers
```
4. Create pvc with this sc
5. Check the driver log
