### ISSUE TITLE
[cinder-csi-plugin] Pod start failed by MountVolume.SetUp failed

### ISSUE THREAD

**Issue by lfdominguez** [kubernetes/cloud-provider-openstack#1478]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Pod can't run because unmounted volume.

1- The deploy create a PVC that is bound
![image](https://user-images.githubusercontent.com/5604131/114318661-09a19880-9adc-11eb-9087-5c6ba4a50e08.png)
![image](https://user-images.githubusercontent.com/5604131/114318672-22aa4980-9adc-11eb-8f01-bd7244346e3b.png)

2- The volume is created on OpenStack Cinder (check the volume name):
![image](https://user-images.githubusercontent.com/5604131/114318712-4bcada00-9adc-11eb-8e12-01cbf08c05fc.png)

3- Pod is scheduled to node `k8s-3` where is the volume mounted (see prev photo):
![image](https://user-images.githubusercontent.com/5604131/114318765-8a609480-9adc-11eb-8884-dab392275587.png)

4- The pod status show an error about `failed MountVolume.SetUp` in a inexistent `mount` file:
![image](https://user-images.githubusercontent.com/5604131/114318806-ab28ea00-9adc-11eb-89b5-0d4744f674e6.png)

**What you expected to happen**:
Pod start with the cinder volumed attached

**How to reproduce it**:
Deploy a stateful set with this `volumeClaimTemplates` template:
```yaml
volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "20Gi"
```

**Anything else we need to know?**:
I have anothers pods using the PVCs correctly. The cluster is a minik8s from canonical where the kubernetes binaries live inside `/var/snap/microk8s` so I changed the variables inside the CSI provider yaml files, here are the file changed (cinder-csi-nodeplugin.yaml):

```yaml
# This YAML file contains driver-registrar & csi driver nodeplugin API objects,
# which are necessary to run csi nodeplugin for cinder.

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-cinder-nodeplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-cinder-nodeplugin
  template:
    metadata:
      labels:
        app: csi-cinder-nodeplugin
    spec:
      tolerations:
        - operator: Exists
      serviceAccount: csi-cinder-node-sa
      hostNetwork: true
      containers:
        - name: node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v1.3.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/cinder.csi.openstack.org /registration/cinder.csi.openstack.org-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/snap/microk8s/common/var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.1.0
          args:
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: cinder-csi-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: docker.io/k8scloudprovider/cinder-csi-plugin:latest
          args:
            - /bin/cinder-csi-plugin
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloud-config=$(CLOUD_CONFIG)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: CLOUD_CONFIG
              value: /etc/config/cloud.conf
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          # The probe
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: "HostToContainer"
            - name: secret-cinderplugin
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/snap/microk8s/common/var/lib/kubelet/plugins/cinder.csi.openstack.org
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/snap/microk8s/common/var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/snap/microk8s/common/var/lib/kubelet
            type: Directory
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - name: secret-cinderplugin
          secret:
            secretName: cloud-config
```

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.2.2@latest
- OpenStack version: Ussuri
- Others: Minik8s as Kubernetes Version deployed with snap.
