### ISSUE TITLE
[cinder-csi-plugin] Cannot read ca.pem from /etc/ssl/certs/

### ISSUE THREAD

**Issue by Gmerold** [kubernetes/cloud-provider-openstack#1546]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

Hello,
While trying to install **cinder-csi-plugin** I've encountered a problem with reading my OpenStack cert.
From **csi-cinder-controllerplugin** pod:
`I0528 17:54:22.308841       1 main.go:118] Failed to GetOpenStackProvider: open /etc/ssl/certs/ca.pem: no such file or directory`
From **csi-cinder-nodeplugin** pod:
`W0528 17:55:22.699117       1 main.go:108] Failed to GetOpenStackProvider: failed to read and parse /etc/ssl/certs/ca.pem certificate: open /etc/ssl/certs/ca.pem: no such file or directory`

Surprisingly, **ca.pem** is just where it should be:
```
ubuntu@master-node-01:~$ sudo ls -al /etc/ssl/certs/ | grep ca.pem
-rw-r--r-- 1 root root  25570 May 27 20:28 ca.pem 
```

PODs status:
```
kube-system   csi-cinder-controllerplugin-0              2/4     CrashLoopBackOff   51         81m
kube-system   csi-cinder-nodeplugin-2875s                2/3     CrashLoopBackOff   7          31m
kube-system   csi-cinder-nodeplugin-gwg6n                2/3     CrashLoopBackOff   10         33m
```

I've tried changing ownership of the cert to ubuntu and privileges to different values, including 777. It didn't help. 
Somehow, **openstack-cloud-controller-manager** didn't have problems reading the cert. 
Any idea what might be the issue?
Any hints greatly appreciated.

**Comment by jichenjc** [comment]
I guess you might want to check 

https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md

```
NOTE: If using certs(ca-file), make sure to update the manifests (controller and node plugin) to mount the location of certs as volume onto container as well.
```

see my example (my cert is in /etc/cacert folder)
```
          volumeMounts:
          ....
          - name: cacert
              mountPath: /etc/cacert
              readOnly: true

     volumes:   
        ....
        - name: cacert
          hostPath:
            path: /etc/cacert
```
