### ISSUE TITLE
[manila-csi-plugin] Unable to set metadata with appendShareMetadata

### ISSUE THREAD

**Issue by JPRbrs** [kubernetes/cloud-provider-openstack#1621]
> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I've tried to create a NFS share with Manila CSI Plugin passing autogrow key in metadata but the share is created without metadata

**What you expected to happen**:
The share has autogrow enabled and metadata is present when running manila metadata-show share-ID

**How to reproduce it**:
Deploy the following manifest in a K8s Cluster with Manila CSI plugin installed
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-csi-autogrow
parameters:
  csi.storage.k8s.io/node-publish-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-publish-secret-namespace: manila-csi
  csi.storage.k8s.io/node-stage-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: manila-csi
  csi.storage.k8s.io/provisioner-secret-name: csi-manila-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: manila-csi
  type: default_share_type
  appendShareMetadata: "{\"autogrow\": \"80\"}"
allowVolumeExpansion: True
provisioner: nfs.manila.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-csi-autogrow
  namespace: manila-poc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manila-csi-autogrow
 
---
apiVersion: v1
kind: Pod
metadata:
  name: manila-csi-poc
  namespace: manila-poc
spec:
  containers:
    - name: web-server
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: manila-csi-autogrow
        readOnly: false

```

**Anything else we need to know?**:
manila metadata set autogrow=80 works fine
I've also tried to set both autogrow and original_size to no avail

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 
- OpenStack version: 3.18
- Others: 
  - K8s server : 1.18
  - csi-provisioner:v1.4.0
  - csi-node-driver-registrar:v1.1.0

**Comment by gman0** [comment]
@JPRbrs thanks for reporting. I can't reproduce this with latest manila-csi v1.21:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devstack-cephfs
provisioner: cephfs.manila.csi.openstack.org
allowVolumeExpansion: true
parameters:
  type: cephfstype
  appendShareMetadata: "{\"autogrow\": \"80\"}"
  
  csi.storage.k8s.io/provisioner-secret-name: devstack-manila
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: devstack-manila
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: devstack-manila
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: devstack-manila
  csi.storage.k8s.io/node-publish-secret-namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-cephfs-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: devstack-cephfs
```

```
$ manila show 7aed54c2-056c-420e-917a-20170b32a4cf
+---------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| Property                              | Value                                                                                                                |
+---------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| id                                    | 7aed54c2-056c-420e-917a-20170b32a4cf                                                                                 |
| size                                  | 1                                                                                                                    |
| availability_zone                     | manila-zone-0                                                                                                        |
| created_at                            | 2021-08-13T07:46:49.807161                                                                                           |
| status                                | available                                                                                                            |
| name                                  | pvc-6b9b0536-11a4-4af2-b477-2eb4ea68e569                                                                             |
| description                           | provisioned-by=manila.csi.openstack.org                                                                              |
| project_id                            | 0819fc21aad64c16910bda9bc8adca9b                                                                                     |
| snapshot_id                           | None                                                                                                                 |
| share_network_id                      | None                                                                                                                 |
| share_proto                           | CEPHFS                                                                                                               |
| metadata                              | {'autogrow': '80'}                                                                                                   |
| share_type                            | f0b6d45c-c80f-40bf-b93c-a12c72dea349                                                                                 |
| is_public                             | False                                                                                                                |
| snapshot_support                      | True                                                                                                                 |
| task_state                            | None                                                                                                                 |
| share_type_name                       | cephfstype                                                                                                           |
| access_rules_status                   | active                                                                                                               |
| replication_type                      | None                                                                                                                 |
| has_replicas                          | False                                                                                                                |
| user_id                               | 51f6fdf9f0bf4ec5902a063046d69a82                                                                                     |
| create_share_from_snapshot_support    | True                                                                                                                 |
| revert_to_snapshot_support            | False                                                                                                                |
| share_group_id                        | None                                                                                                                 |
| source_share_group_snapshot_member_id | None                                                                                                                 |
| mount_snapshot_support                | False                                                                                                                |
| progress                              | 100%                                                                                                                 |
| share_server_id                       | None                                                                                                                 |
| host                                  | rvasek-devstack@cephfsnative1#cephfs                                                                                 |
| export_locations                      |                                                                                                                      |
|                                       | id = 850cf97c-260d-42fd-af17-3873876555c0                                                                            |
|                                       | path = 188.184.74.8:6789:/volumes/_nogroup/5341094c-7295-45bf-bb74-7f3446814654/d225d22d-7d40-46f8-8099-657b3804cb03 |
|                                       | preferred = False                                                                                                    |
|                                       | share_instance_id = 5341094c-7295-45bf-bb74-7f3446814654                                                             |
|                                       | is_admin_only = False                                                                                                |
+---------------------------------------+----------------------------------------------------------------------------------------------------------------------+
```

What manila-csi version are you using?
