### ISSUE TITLE
[manila-csi-plugin] Delete retain policy does not delete shares in Openstack

### ISSUE THREAD

**Issue by JPRbrs** [kubernetes/cloud-provider-openstack#1696]
/kind bug

**What happened**: Despite Volume deletion being supported by both CSI-NFS-driver and Manila-CSI-driver, I've observed that deleting a pvc which uses a StorageClass with retainpolicy Delete does not delete the share from OpenStack
See manifest used below:

**What you expected to happen**: I expected the share in Openstack to be deleted along the k8s PVC (please correct me if that is not the expected behaviour"

**How to reproduce it**:
Deploy the following manifest in a k8s cluster (version 1.18.5) which is using a Openstack 3.18.0 and manila 1.27.0:
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-csi-autogrow
parameters:
  csi.storage.k8s.io/node-publish-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-publish-secret-namespace: manila-csi
  csi.storage.k8s.io/node-stage-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: manila-csi
  csi.storage.k8s.io/provisioner-secret-name: csi-manila-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: manila-csi
  type: default_share_type
  appendShareMetadata: "{\"autogrow\": \"80\"}"
allowVolumeExpansion: True
provisioner: nfs.manila.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-csi-autogrow
  namespace: manila-csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manila-csi-autogrow
```

**Anything else we need to know?**:

**Environment**:
- openstack-manila-csi: 1.3.3
- OpenStack version: 3.18.0
- Others: k8s cluster version 1.18.5, Manila 1.27.0
