### ISSUE TITLE
[manila-csi-plugin] Unable to resize volumes with CSI-NFS-driver and manila-CSI-plugin

### ISSUE THREAD

**Issue by JPRbrs** [kubernetes/cloud-provider-openstack#1697]
/kind feature

**What happened**:
I'm unable to resize an NFS volume created with ManilaCSI and CSI-NFS-driver

`
Warning  ExternalExpanding      10s                    volume_expand Ignoring the PVC: didn't find a plugin capable of expanding the 
olume; waiting for an external controller to process this PVC.
`

**What you expected to happen**:
Volume gets expanded

**How to reproduce it**:
Create a pvc and a storage class with the code below.
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-csi-autogrow
parameters:
  csi.storage.k8s.io/node-publish-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-publish-secret-namespace: manila-csi
  csi.storage.k8s.io/node-stage-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: manila-csi
  csi.storage.k8s.io/provisioner-secret-name: csi-manila-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: manila-csi
  type: default_share_type
  appendShareMetadata: "{\"autogrow\": \"80\"}"
allowVolumeExpansion: True
provisioner: nfs.manila.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-csi-autogrow
  namespace: manila-csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manila-csi-autogrow
```

Then try to expand the pvc with:
```
kubectl patch pvc manila-csi-autogrow -p '{"spec":{"resources":{"requests":{"storage":"2Gi"}}}}' 
```

**Anything else we need to know?**:
As per some of the resolved issues in this repo (https://github.com/kubernetes/cloud-provider-openstack/pull/1579) I assume this should be possible but I've also seen that the supported NFS CSI driver (https://github.com/kubernetes-csi/csi-driver-nfs) does not support volume expansion. I couldn't find any other CSI-NFS-driver to use. What am I missing?

**Environment**:
openstack-manila-csi: 1.22.0
OpenStack version: 3.18.0
K8s cluster version 1.18.5
CSI-NFS-driver: chart version 3.0.0 - https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/charts

Many thanks in advance
