### ISSUE TITLE
[openstack-cloud-controller-manager] Serviceaccount cannot patch resource "services"

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1722]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

create a LB follow 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

```
kind: Service
apiVersion: v1
metadata:
  name: hello-world
  annotations:
    service.beta.kubernetes.io/brightbox-load-balancer-healthcheck-request: /
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web
```

in logs seems 
```
E1226 09:11:24.522851       1 controller.go:307] error processing service example/hello-world (will retry): failed to ensure load balancer: failed to patch service object example/hello-world: services "hello-world" is forbidden: User "system:serviceaccount:kube-system:cloud-provider-openstack" cannot patch resource "services" in API group "" in the namespace "example"
I1226 09:11:24.523070       1 event.go:291] "Event occurred" object="example/hello-world" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: failed to patch service object example/hello-world: services \"hello-world\" is forbidden: User \"system:serviceaccount:kube-system:cloud-provider-openstack\" cannot patch resource \"services\" in API group \"\" in the namespace \"example\""
```

it's weird why `"system:serviceaccount:kube-system:cloud-provider-openstack\"` is used

I created following command
```
kubectl create clusterrolebinding my-1 --clusterrole=system:cloud-controller-manager --serviceaccount=kube-system:cloud-provider-openstack
```

and it works fine in the LB after the clusterrolebinding created 
it's weird why `kube-system:cloud-provider-openstack` is created 
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
opening this to track the problem as this is first time I saw this kind of issue

**Comment by jacksgt** [comment]
Hello,

I'm still seeing this error with the release-1.23 version (`0807b16`) and the latest Helm chart from master (`d0f3cad`).

`kubectl create svc loadbalancer mv-lb` results in:

```
E0224 09:41:12.619482       1 controller.go:310] error processing service default/mv-lb (will retry): failed to ensure load balancer: failed to patch service object default/mv-lb: services "mv-lb" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot patch resource "services" in API group "" in the namespace "default"
```

The daemonset is using the service account `openstack-cloud-controller-manager`:

```
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: openstack-cloud-controller-manager
        component: controllermanager
        release: openstack-cloud-controller
    template:
      metadata:
        annotations:
          checksum/config: ed0a9897da2498221063e2119422aafa31b3f2f255035fcdf6774b8f22dd32fd
          kubectl.kubernetes.io/restartedAt: "2022-02-24T10:39:33+01:00"
        creationTimestamp: null
        labels:
          app: openstack-cloud-controller-manager
          chart: openstack-cloud-controller-manager-1.2.0
          component: controllermanager
          heritage: Helm
          release: openstack-cloud-controller
      spec:
        containers:
        - args:
          - /bin/openstack-cloud-controller-manager
          - --v=2
          - --cloud-config=$(CLOUD_CONFIG)
          - --cloud-provider=openstack
          - --use-service-account-credentials=true
          - --controllers=service
          - --bind-address=0.0.0.0
          - --cluster-name=clu-jack-dev
          env:
          - name: CLOUD_CONFIG
            value: /etc/config/cloud.conf
          image: registry.cern.ch/jhensche/occm:cern-1.23-dev
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: openstack-cloud-controller-manager
          ports:
          - containerPort: 10258
            hostPort: 10258
            name: http
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/config
            name: cloud-config-volume
            readOnly: true
        dnsPolicy: ClusterFirst
        hostNetwork: true
        nodeSelector:
          node-role.kubernetes.io/master: ""
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: openstack-cloud-controller-manager
        serviceAccountName: openstack-cloud-controller-manager
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        volumes:
        - name: cloud-config-volume
          secret:
            defaultMode: 420
            secretName: cloud-config
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
```

which has the following ClusterRole / ClusterRoleBinding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  creationTimestamp: "2022-02-02T10:40:55Z"
  labels:
    argocd.argoproj.io/instance: openstack-cloud-controller
  name: system:openstack-cloud-controller-manager
  resourceVersion: "21118211"
  uid: eff6fcf3-cd16-45fe-8aab-b65805e92b01
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2022-02-02T10:40:55Z"
  labels:
    argocd.argoproj.io/instance: openstack-cloud-controller
  name: system:openstack-cloud-controller-manager
  resourceVersion: "21118235"
  uid: b004e774-5ff8-4391-88e4-ccf39e231a8d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openstack-cloud-controller-manager
subjects:
- kind: ServiceAccount
  name: openstack-cloud-controller-manager
  namespace: openshift-cern-cloud-controller
```

In particular the ClusterRole has this part, so it should be allowed to modify services in all namespaces:
```
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - patch
  - update
  - watch
```

Since the controller is running witht the service account "openstack-cloud-controller-manager", I don't understand why it identifies itself as "system:serviceaccount:kube-system:cloud-controller-manager" (especially since it's *NOT* running in the kube-system namespace).
