### ISSUE TITLE
[occm] MonitorPort not working

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#1749]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Updated from 1.22.0 to 1.23.0

**What you expected to happen**:

I expect that loadbalancer services should continue working as-is

It looks like it is working for start. However, after sometime I can see that for somereason the MonitorPort (`monitor_port`) is cleaned from the pool members.

Logs https://gist.github.com/zetaab/6a5759cdaca2885498eda2d58bef5908

I added debug row https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/loadbalancer.go#L1246 which prints the content of members and svcConf

as you can see from logs monitorport is there for first 2-3 minutes. After that monitorport is null. When the monitor_port is empty the healthchecks will start failing and members will go to `ERROR` state which leads downtime to loadbalancer itself.

When checking the service itself I can see the healthCheckNodePort defined

```
% kubectl get svc ingress-nginx-internal -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.openstack.org/connection-limit: "100000"
    loadbalancer.openstack.org/floating-subnet: ext-ha-v4
    loadbalancer.openstack.org/keep-floatingip: "true"
    loadbalancer.openstack.org/proxy-protocol: "true"
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: kaas-batch
    app.kubernetes.io/name: ingress-nginx-internal
    app.kubernetes.io/part-of: ingress-nginx-internal
    ingress.class: internal
  name: ingress-nginx-internal
  namespace: ingress-nginx-internal
spec:
  ...
  externalTrafficPolicy: Local
  healthCheckNodePort: 31652
  ...
  selector:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: kaas-batch
    app.kubernetes.io/name: ingress-nginx-internal
    app.kubernetes.io/part-of: ingress-nginx-internal
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.222.159.48
```

cc @databus23
