### ISSUE TITLE
[occm][lb] Incorrect cluster name

### ISSUE THREAD

**Issue by poussa** [kubernetes/cloud-provider-openstack#1807]
/kind bug

**What happened**:

https://github.com/kubernetes/cloud-provider/blob/7f90ee552e3b169ccbdd131cce3ce3574f0afc8b/cloud.go#L160

The above spec says that the cluster name should come from the `kube-control-manager`

I have a cluster (via CAPO) which has `kube-control-manager` arg:

`      --cluster-name=istio-2`

However, when occm creates a LB, I see in the logs:

```console
I0304 14:29:55.159348       1 loadbalancer.go:1915] EnsureLoadBalancer(kubernetes, istio-system/istio-ingressgateway)
```
That is, the cluster name is `kubernetes` not `istio-2`

This causes an issue when you have multiple clusters and have same LB service (e.g. istio-ingressgateway) is some of the clusters. Only one LB is created and it is shared between the clusters. Obviously this does not work.

**What you expected to happen**:

The cluster name comes what the `kube-control-manager` says it is. Each cluster gets it's own LB even if the LB service namespace/name is the same.

**How to reproduce it**:

Always. This was not an issue in 1.20

**Anything else we need to know?**:

**Environment**:
1.22

**Comment by jichenjc** [comment]
https://github.com/kubernetes/cloud-provider/blob/master/app/core.go#L88

this comes from `completedConfig.ComponentConfig.KubeCloudShared.ClusterName`

I assume you need external cloud providder (kube-cloud-manager) instead of kube-config-manager to utilize the clusterName param to make OCCM honor that

**Comment by poussa** [comment]
@jichenjc thanks for the answer. However, it is not clear to me how to do what you suggested.

I deployed the occm as described [here](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#deploy-a-kubernetes-cluster-with-openstack-cloud-controller-manager-using-kubeadm).

Why that is not enough? What is missing?

How can I deploy external cloud provider (kube-cloud-manager) as you suggested? I thought occm is the external cloud provider.

**Comment by jichenjc** [comment]
kube-control-manager is different to kube-cloud-manager (OCCM)
e.g this is kube-controller manager and you are using OCCM and you mentioned param is on kube-control-manager
```
 have a cluster (via CAPO) which has kube-control-manager arg:

--cluster-name=istio-2
```

```
kube-system   kube-controller-manager-m1                     1/1     Running   0          5d2h
```

so My *guess* is whether the param should be added to OCCM

**Comment by poussa** [comment]
okay, I now understand what you mean by kube-control-manager and kube-cloud-manager (occm)

I am using cluster api for openstack (capo) and follow the instructions [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/topics/external-cloud-provider.md).

The relevant pods I get are:

```console
kube-system    kube-controller-manager-istio-0-control-plane-sl2zb   1/1     Running   0          3d19h
kube-system    openstack-cloud-controller-manager-976w6              1/1     Running   0          3d19h
```
I would imagine that the `kube-controller-manager-istio-0-control-plane-sl2zb` (kube-control-manager) would pass the clusterName (`istio-0`) to `openstack-cloud-controller-manager-976w6` (kube-cloud-manager). But that is not happening. ClusterName is always `kubernetes` and the different load balancers in different clusters inference with each other.

Is that the same as "param should be added to occm"?

**Comment by jichenjc** [comment]
please check this 

```
# ./openstack-cloud-controller-manager -h | grep cluster-name
      --cluster-name string                      The instance prefix for the cluster. (default "kubernetes")
```

I co-wrote the doc you mentioned in CAPI , so it's just an example

my guess is you need download this file , and update the param with above param
then apply the file again
```
kubectl --kubeconfig=./${CLUSTER_NAME}.kubeconfig apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yam
```

**Comment by poussa** [comment]
I think we are getting closer to the solution/problem. As I said, this used to for for me in 1.20 version. However, in 1.20 I have been using a deployment file, which I did not created myself, containing the following:

```yaml
      containers:
        - name: openstack-cloud-controller-manager
          image: myregistry/k8scloudprovider/openstack-cloud-controller-manager:v1.20.2
          args:
            - /bin/openstack-cloud-controller-manager
            - --v=1
            - --cluster-name=$(CLUSTER_NAME)
            - --cloud-config=$(CLOUD_CONFIG)
            - --cloud-provider=openstack
            - --use-service-account-credentials=true
            - --bind-address=127.0.0.1
# ...
          env:
            - name: CLOUD_CONFIG
              value: /etc/config/cloud.conf
            - name: CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

As you can see the cluster name is set automatically. However, I am not able to find that version in this repo. Do you know why you don't set the cluster name like the above snippet? 

Your suggestion works but is manual editing. My cluster creation is automated and will be part of a CI/CD pipeline so I am looking for more convenient way to pass the cluster name.
