### ISSUE TITLE
[cinder-csi-plugin] nodeaffinity always show topology.cinder.csi.openstack.org/zone in [nova]

### ISSUE THREAD

**Issue by polingsky** [kubernetes/cloud-provider-openstack#1841]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I defined a storageclass

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-storageclass
provisioner: cinder.csi.openstack.org
allowedTopologies:
- matchLabelExpressions:
  - key: topology.cinder.csi.openstack.org/zone
    values:
    - NOVA_ZONE
```

Then I defined pvc 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myvol-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-storageclass
```
Then I use kubectl describe pv { myvol-2-xxxxx}

I found the 
```
Node Affinity:     
  Required Terms:  
    Term 0:        topology.cinder.csi.openstack.org/zone in [nova]
```
topology.cinder.csi.openstack.org/zone in [nova]  is still displayed in nova 

**What you expected to happen**:

I expecyted it will show topology.cinder.csi.openstack.org/zone in [NOVA_ZONE]

My node label with 
**topology.cinder.csi.openstack.org/zone=NOVA_ZONE**
the NOVA_ZONE is real zone in my openstack

**How to reproduce it**:

**Anything else we need to know?**:
docker image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: k8scloudprovider/openstack-cloud-controller-manager:v1.15.0
- OpenStack version: Queens
- Others:
