### ISSUE TITLE
[occm] Mounting ca-certs is mostly broken

### ISSUE THREAD

**Issue by kopiczko** [kubernetes/cloud-provider-openstack#1923]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I created a CAPO cluster using Flatcar and OCCM was failing because it didn't have correct certificates. The /etc/ssl/certs contains only symlinks in Flatcar linux.

**What you expected to happen**:
Work.

**How to reproduce it**:
Run on host OS where /etc/ssl/certs contains only symlinks.

**Anything else we need to know?**:
I guess the simple answer is: yeah but it works on other operating systems and Flatcar is quite specific.

That's true but:

On Ubuntu (which I guess is a popular choice) only one file is not a symlink. It's /etc/ssl/certs/ca-certificates.crt.

I created a pod like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pawel
spec:
  containers:
  - image: ubuntu:latest
    name: pawel
    args:
    - /bin/sh
    - -xc
    - sleep 999999
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: Directory
    name: ca-certs
```

And then from:

```
$ k exec -it pawel -- bash
root@pawel:/# ls /etc/ssl/certs
```

<img width="1890" alt="Screenshot 2022-06-15 at 19 24 03" src="https://user-images.githubusercontent.com/4608994/173898258-fa009459-a01f-440e-a4f9-5b32b23ec405.png">

I'd like to get rid of `ca-certs` mount from https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/values.yaml as in my opinion it doesn't serve any purpose. 

One can argue this would be a breaking change but [the certs are actually installed in docker image](https://github.com/kubernetes/cloud-provider-openstack/blob/8ea8cfb8321246d3f05fcbedab668aa330028575/cluster/images/openstack-cloud-controller-manager/Dockerfile.build#L17) and then overwritten by the mount.

If someone really needs to mount a cert from the host path (e.g. they use self-signed cert available in the image) they can always mount it as a file. I believe this is a better approach than mounting tons of broken symlinks.

**Environment**:
- openstack-cloud-controller-manager
(or other related binary) version:
- OpenStack version:
- Others:
