### ISSUE TITLE
[occm] Loadbalancer Classes are not working with internal Loadbalancern

### ISSUE THREAD

**Issue by shaardie** [kubernetes/cloud-provider-openstack#1961]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

If setting the annotations `service.beta.kubernetes.io/openstack-internal-load-balancer: true` and `loadbalancer.openstack.org/class: someClass`, the class is ignored and the default loadbalancer settings are used.

**What you expected to happen**:

If I set a Loadbalancer Class on a Kubernetes Service, I expect it to be used. Of cource Floating IP Settings are kind of pointless, but I still want to be able to change subnet-id, etc.

**How to reproduce it**:

Create a Kubernetes Service with

```yaml
metadata:
  annotations:
    loadbalancer.openstack.org/class: someClass
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
```

and see how the configuration in the `someClass` Loadbalancer class is going to be ignored.

**Anything else we need to know?**:

For IPv6 we are not using Floating IP, but routing the IPv6 Subnets directly into Openstack. For this szenario we use internal loadbalancer, because we do not need the Floating IPs.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.23.4
- OpenStack version:
- Others:
