### ISSUE TITLE
[manila-csi-plugin] Status field READYTOUSE not becoming true for VolumeSnapshot

### ISSUE THREAD

**Issue by jknipper** [kubernetes/cloud-provider-openstack#2016]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The `READYTOUSE` status field for a newly created `VolumeSnapshot` is not becoming `true`.

```
NAME          READYTOUSE   SOURCEPVC        SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS    SNAPSHOTCONTENT                                    CREATIONTIME   AGE
my-snapshot   false        manila-nfs-pvc                                         csi-manila-nfs   snapcontent-a1d193f6-8999-4da7-b105-3e025c15f38e                  121m
```

Although the snapshot is successfully created in Openstack and `VolumeSnapshotContent` `READYTOUSE` status field becomes `true`. 

**What you expected to happen**:

`READYTOUSE` status field in `VolumeSnapshot` resource becomes `true` eventually and the snapshot can be used to create a `PersistentVolumeClaim`.

**How to reproduce it**:

I'm using chart version `1.6.0` with the following `VolumeSnapshotClass`:

```
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: nfs.manila.csi.openstack.org
kind: VolumeSnapshotClass
metadata:
  name: csi-manila-nfs
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: manila-csi-plugin
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
```

`StorageClass`:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-manila-nfs
parameters:
  availability: eu-nl-1b
  csi.storage.k8s.io/controller-expand-secret-name: manila-csi-plugin
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: manila-csi-plugin
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: manila-csi-plugin
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  nfs-shareClient: 10.180.0.0/16
  shareNetworkID: 32e1a7f3-aaf7-4cb2-81a2-34b72c49f085
  type: default
provisioner: nfs.manila.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

After applying the following resource the status field never switches to `true`

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: my-snapshot
spec:
  volumeSnapshotClassName: csi-manila-nfs
  source:
    persistentVolumeClaimName: manila-nfs-pvc
```

**Anything else we need to know?**:

Everything else like create/delete/extend works as expected.

**Environment**:

```
Kubernetes v1.25.2
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
k8scloudprovider/manila-csi-plugin:v1.25.2
```
