### ISSUE TITLE
[cinder-csi-plugin] Filesystem not resized

### ISSUE THREAD

**Issue by cgallay** [kubernetes/cloud-provider-openstack#2059]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Expanding a PVC did not increase the filesystem size. All logs seem green but actual size within the pod stays unchanged.

**What you expected to happen**:
Increase filesystem from 1Gi to 2Gi for the test pod below.

**How to reproduce it**:
Helm chart 2.3.0
```
csi:
  attacher:
    resources:
      requests:
        cpu: 20m
        memory: 32M
  provisioner:
    resources:
      requests:
        cpu: 20m
        memory: 32M
  snapshotter:
    resources:
      requests:
        cpu: 20m
        memory: 32M
  resizer:
    resources:
      requests:
        cpu: 20m
        memory: 32M
  livenessprobe:
    resources:
      requests:
        cpu: 20m
        memory: 32M
  plugin:
    nodePlugin:
      tolerations: []
    controllerPlugin:
      replicas: 2
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - effect: NoExecute
          key: CriticalAddonsOnly
          operator: "Exists"
secret:
  enabled: true
  create: true
  name: cinder-csi-cloud-config
  data:
    cloud.conf: |-
      [Global]
      auth-url = ${auth_url}
      application-credential-name = ${app_name}
      application-credential-id = ${app_id}
      application-credential-secret = ${app_secret}
      region = ${region}
      tenant-id = ${project_id}
      [BlockStorage]
      ignore-volume-az = true
      rescan-on-resize = true # tried without, same result
storageClass:
  enabled: false        
```

Storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder-delete
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  availability: nova
```

Following the [example](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/examples.md#volume-expansion-example):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-cinderplugin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-delete
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/html
          name: csi-data-cinderplugin
  volumes:
    - name: csi-data-cinderplugin
      persistentVolumeClaim:
        claimName: csi-pvc-cinderplugin
        readOnly: false
```

Resize: 1Gi to 2Gi

Same result before and after:
```
kubectl exec nginx -- df -h /var/lib/www/html
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdl        974M   24K  958M   1% /var/lib/www/html
```

Controller plugin:
```
I1219 13:06:10.782927       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"testns", Name:"csi-pvc-cinderplugin", UID:"4c8898b8-df67-48d8-835c-364624c866d2", APIVersion:"v1", ResourceVersion:"3401456", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-4c8898b8-df67-48d8-835c-364624c866d2
I1219 13:06:12.321015       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"testns", Name:"csi-pvc-cinderplugin", UID:"4c8898b8-df67-48d8-835c-364624c866d2", APIVersion:"v1", ResourceVersion:"3401456", FieldPath:""}): type: 'Normal' reason: 'FileSystemResizeRequired' Require file system resize of volume on nod
```

Node plugin:
```
I1219 13:05:40.216658       1 mount_linux.go:525] Disk "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3e3af681-a134-4ab5-bb6e-15ce8acada29" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3e3af681-a134-4ab5-bb6e-15ce8acada29]
I1219 13:05:40.558868       1 mount_linux.go:535] Disk successfully formatted (mkfs): ext4 - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3e3af681-a134-4ab5-bb6e-15ce8acada29 /var/lib/kubelet/plugins/kubernetes.io/csi/cinder.csi.openstack.org/d40a20a10b17cf421e36d78fed6065c218163f498b54e2515f0e3f38b693aca5/globalmount
I1219 13:06:33.046015       1 resizefs_linux.go:71] Device /dev/sdl resized successfully
```

Events:
```
testns   17m         Normal    WaitForFirstConsumer         persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     waiting for first consumer to be created before binding
testns   17m         Normal    ExternalProvisioning         persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     waiting for a volume to be created, either by external provisioner "cinder.csi.openstack.org" or manually created by system administrator
testns   17m         Normal    Provisioning                 persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     External provisioner is provisioning volume for claim "testns/csi-pvc-cinderplugin"
testns   17m         Normal    ProvisioningSucceeded        persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     Successfully provisioned volume pvc-4c8898b8-df67-48d8-835c-364624c866d2
testns   17m         Normal    Scheduled                    pod/nginx                                                                                                                      Successfully assigned testns/nginx to expo-prd-a-1
testns   17m         Normal    SuccessfulAttachVolume       pod/nginx                                                                                                                      AttachVolume.Attach succeeded for volume "pvc-4c8898b8-df67-48d8-835c-364624c866d2"
testns   17m         Normal    Pulling                      pod/nginx                                                                                                                      Pulling image "nginx"
testns   17m         Normal    Pulled                       pod/nginx                                                                                                                      Successfully pulled image "nginx" in 4.401861383s
testns   17m         Normal    Started                      pod/nginx                                                                                                                      Started container nginx
testns   17m         Normal    Created                      pod/nginx                                                                                                                      Created container nginx
testns   17m         Normal    Resizing                     persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     External resizer is resizing volume pvc-4c8898b8-df67-48d8-835c-364624c866d2
testns   17m         Warning   ExternalExpanding            persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
testns   17m         Normal    FileSystemResizeRequired     persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     Require file system resize of volume on node
testns   16m         Normal    FileSystemResizeSuccessful   persistentvolumeclaim/csi-pvc-cinderplugin                                                                                     MountVolume.NodeExpandVolume succeeded for volume "pvc-4c8898b8-df67-48d8-835c-364624c866d2" expo-prd-a-1
testns   16m         Normal    FileSystemResizeSuccessful   pod/nginx                                                                                                                      MountVolume.NodeExpandVolume succeeded for volume "pvc-4c8898b8-df67-48d8-835c-364624c866d2" expo-prd-a-1
```

kubectl:
```
kubectl get pvc
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
csi-pvc-cinderplugin               Bound    pvc-4c8898b8-df67-48d8-835c-364624c866d2   2Gi        RWO            csi-cinder-delete   5m
```

OpenStack:
```
+------------------------------+-----------------------------------------------+
| Field                        | Value                                         |
+------------------------------+-----------------------------------------------+
| attachments                  | [{'id':                                       |
|                              | '3e3af681-a134-4ab5-bb6e-15ce8acada29',       |
|                              | 'attachment_id':                              |
|                              | '4213d30e-0311-4d6e-b087-aad9dbb68155',       |
|                              | 'volume_id':                                  |
|                              | '3e3af681-a134-4ab5-bb6e-15ce8acada29',       |
|                              | 'server_id':                                  |
|                              | '66c31dad-e801-458e-8b90-314f943219d5',       |
|                              | 'host_name': None, 'device': '/dev/sdl',      |
|                              | 'attached_at': '2022-12-19T13:05:38.000000'}] |
| availability_zone            | nova                                          |
| bootable                     | false                                         |
| consistencygroup_id          | None                                          |
| created_at                   | 2022-12-19T13:05:36.000000                    |
| description                  | Created by OpenStack Cinder CSI driver        |
| encrypted                    | False                                         |
| id                           | 3e3af681-a134-4ab5-bb6e-15ce8acada29          |
| multiattach                  | False                                         |
| name                         | pvc-4c8898b8-df67-48d8-835c-364624c866d2      |
| os-vol-tenant-attr:tenant_id | e388838752254d669887b10c871eae5b              |
| properties                   | cinder.csi.openstack.org/cluster='kubernetes' |
|                              | , csi.storage.k8s.io/pv/name='pvc-4c8898b8-   |
|                              | df67-48d8-835c-364624c866d2',                 |
|                              | csi.storage.k8s.io/pvc/name='csi-pvc-         |
|                              | cinderplugin',                                |
|                              | csi.storage.k8s.io/pvc/namespace='testns'     |
| replication_status           | None                                          |
| size                         | 2                                             |
| snapshot_id                  | None                                          |
| source_volid                 | None                                          |
| status                       | in-use                                        |
| type                         | CEPH_1_perf1                                  |
| updated_at                   | 2022-12-19T13:06:11.000000                    |
| user_id                      | REDACTED                                      |
+------------------------------+-----------------------------------------------+
```

**Anything else we need to know?**:
I was unable to find a workaround, that would be critical to find. What other logs/debug steps can I try?

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: Cinder 2.3.0
- OpenStack version: -
- Others: -
