### ISSUE TITLE
client-keystone-auth: Project name is missing for authentication

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/cloud-provider-openstack#240]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
client-keystone-auth doesn't work

**What you expected to happen**:
client-keystone-auth should work after kubeconfig configuration.

**How to reproduce it (as minimally and precisely as possible)**:
1. `kubectl config set-credentials openstackuser-clientauth`
2. Edit ~/.kube/config file, add the information client-keystone-auth needs

```yaml
users:
- name: openstackuser-clientauth
  user:
    exec:
      command: "/home/ubuntu/client-keystone-auth"
      apiVersion: "client.authentication.k8s.io/v1alpha1"
      env:
        - name: "OS_USERNAME"
          value: "demo"
        - name: "OS_PASSWORD"
          value: "password"
        - name: "OS_PROJECT_NAME"
          value: "demo"
        - name: "OS_TENANT_NAME"
          value: "demo"
        - name: "OS_REGION_NAME"
          value: "RegionOne"
        - name: "OS_IDENTITY_API_VERSION"
          value: "3"
        - name: "OS_DOMAIN_NAME"
          value: "default"
      args:
        - "--keystone-url=http://10.140.81.86/identity/v3"
        - "--domain-name=default"
```

3. In webhook service policy definition, allow user `demo` with `kube-viewer` role to get pods
4. Run `kubectl get pods`, the authorization failed.

```shell
$ kubectl get po
Keystone auth url is "http://10.140.81.86/identity/v3"
Domain name is "default"
User name is "demo"
Password is set
Error from server (Forbidden): pods is forbidden: User "demo" cannot list pods in the namespace "default"
```

The reason is the token client-keystone-auth gets from keystone is an unscoped token because the project name is not specified when fetching token.
