### ISSUE TITLE
[occm] how do you use the openstack-cloud-controller-manager helm chart?

### ISSUE THREAD

**Issue by till** [kubernetes/cloud-provider-openstack#2432]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I am migrating from the manifests to using the helm chart for our clusters (primarily because the helm chart seems to allow us to keep up to date and customize the paths as needed for our k8s distro.

I am trying to deploy the helm chart (`2.28.0`) with the following values:

```yaml
cluster:
  name: prod
secret:
  enabled: true
  name: cloud-config
  create: false
extraVolumes:
- name: flexvolume-dir
  hostPath:
    path: /opt/libexec/k0s/kubelet-plugins/volume/exec
- name: k8s-certs
  hostPath:
    path: /var/lib/k0s/pki
# Where the additional volumes should be mounted into the pods:
extraVolumeMounts:
  - name: flexvolume-dir
    mountPath: /opt/libexec/k0s/kubelet-plugins/volume/exec
    readOnly: true
  - name: k8s-certs
    mountPath: /var/lib/k0s/pki
    readOnly: true
```

In addition, I create a secret `cloud-config` (in `kube-system`):

```ini
[Global]
username=redacted
password=redacted
auth-url=https://redacted:5000/v3
tls-insecure=true
region=RegionOne
domain-name=redacted
tenant-id=redacted

[LoadBalancer]
use-octavia=true
floating-network-id=redacted
subnet-id=redacted

[BlockStorage]
bs-version=v2

[Networking]
internal-network-name=network-prod
ipv6-support-disabled=true
```

(In addition, I am also using the cinder chart and it seems to succeed there, but certain services fail due to the worker nodes coming up as "uninitialized" still.) 

**What you expected to happen**:

Running cloud controller manager (and no taints on my k8s nodes).

**How to reproduce it**:

see above

**Anything else we need to know?**:

The `DaemonSet` maybe?

```
Name:           openstack-cloud-controller-manager
Selector:       app=openstack-cloud-controller-manager,component=controllermanager,release=openstack-cloud-controller-manager
Node-Selector:  <none>
Labels:         app.kubernetes.io/instance=openstack-cloud-controller-manager
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=openstack-cloud-controller-manager
                app.kubernetes.io/version=v1.28.0
                helm.sh/chart=openstack-cloud-controller-manager-2.28.0
Annotations:    deprecated.daemonset.template.generation: 2
                meta.helm.sh/release-name: openstack-cloud-controller-manager
                meta.helm.sh/release-namespace: kube-system
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=openstack-cloud-controller-manager
                    chart=openstack-cloud-controller-manager-2.28.0
                    component=controllermanager
                    heritage=Helm
                    release=openstack-cloud-controller-manager
  Annotations:      checksum/config: bf42776b3c976e5762a25c440c7615361c3faf25106844e44870eb6ce9a9f4f1
  Service Account:  openstack-cloud-controller-manager
  Containers:
   openstack-cloud-controller-manager:
    Image:      registry.k8s.io/provider-os/openstack-cloud-controller-manager:v1.28.0
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/openstack-cloud-controller-manager
      --v=1
      --cloud-config=$(CLOUD_CONFIG)
      --cluster-name=$(CLUSTER_NAME)
      --cloud-provider=openstack
      --use-service-account-credentials=true
      --controllers=cloud-node,cloud-node-lifecycle,route,service
      --bind-address=127.0.0.1
    Environment:
      CLOUD_CONFIG:  /etc/config/cloud.conf
      CLUSTER_NAME:  prod
    Mounts:
      /etc/config from cloud-config-volume (ro)
      /opt/libexec/k0s/kubelet-plugins/volume/exec from flexvolume-dir (ro)
      /var/lib/k0s/pki from k8s-certs (ro)
  Volumes:
   cloud-config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloud-config
    Optional:    false
   flexvolume-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/libexec/k0s/kubelet-plugins/volume/exec
    HostPathType:  
   k8s-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/k0s/pki
    HostPathType:  
Events:            <none>
```

Maybe the node labels need to be set?

The default values in the chart say:

```yaml
tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
```

But I am not exactly sure if the list of tolerations is interpreted as an "and" or an "or"?
 
**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version: `3.18.5`
- Others:
