### ISSUE TITLE
[cinder-csi-plugin] Support for formatOptions

### ISSUE THREAD

**Issue by heyleke** [kubernetes/cloud-provider-openstack#2469]
/kind feature

**What happened**:
We created a cinder pvc of 1GB and wrote 66000 small files to it, run out of inodes

**What you expected to happen**:
This is caused by inode ratio of ext4 fs being used by cinder-csi
We can control formatOptions through the StorageClass

**How to reproduce it**:
create storageclass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder
parameters:
  availability: nova
provisioner: kubernetes.io/cinder
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
create pvc
write 66000 files to the pvc
df -i

**Anything else we need to know?**:
similar implementation of options:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/48a4f6d713633fc9e79187f06168985d3d463f5a/pkg/driver/node.go#L265

Alternative suggestions to work around this issue (different pvc size, mountoptions,...) are welcome
