### ISSUE TITLE
Unable to mount volumes for pod with the pvc created by cinder-provisioner

### ISSUE THREAD

**Issue by npu21** [kubernetes/cloud-provider-openstack#249]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I create a deployment like this
```
apiVersion: apps/v1beta2
kind: Deployment          
metadata:
  name: mysql-sonar
spec:
  replicas: 1                          
  selector:
    matchLabels:
      app: mysql-sonar                      
  template:
    metadata:
      labels:
        app: mysql-sonar
    spec:
      containers:                       
      - name: mysql-sonar
        image: harbor.iop.com:5000/library/iop/mysql:5.7.22
        args:
          - "--ignore-db-dir=lost+found"      
        ports:
        - containerPort: 3306           
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123456XXX
        volumeMounts:
        - name: mysql-sonar
          mountPath: /var/mysql
      volumes:
      - name: mysql-sonar
        persistentVolumeClaim:
          claimName: mysql-sonar-pvc
```
the pvc mysql-sonar-pvc is create by cinder-provisioner
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-sonar-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-standard-iops
```
and it's bound
mysql-sonar-pvc                              Bound     pvc-4c853f30-9625-11e8-bfa3-0050568860dd   1Gi        RWO            cinder-standard-iops   13m
I can also see it's created successfully in cinder api

> Name:            pvc-4c853f30-9625-11e8-bfa3-0050568860dd
> Labels:          <none>
> Annotations:     cinderVolumeId=2ba19e9b-9430-44d2-8198-dbc6ca28acd5
>                  pv.kubernetes.io/provisioned-by=openstack.org/standalone-cinder
>                  standaloneCinderProvisionerIdentity=openstack.org/standalone-cinder
> StorageClass:    cinder-standard-iops
> Status:          Bound
> Claim:           default/mysql-sonar-pvc
> Reclaim Policy:  Delete
> Access Modes:    RWO
> Capacity:        1Gi
> Message:         
> Source:
>     Type:          RBD (a Rados Block Device mount on the host that shares a pod's lifetime)
>     CephMonitors:  [192.168.4.181:6789 192.168.4.182:6789 192.168.4.183:6789]
>     RBDImage:      volume-2ba19e9b-9430-44d2-8198-dbc6ca28acd5
>     FSType:        
>     RBDPool:       volumes
>     RadosUser:     cinder
>     Keyring:       /etc/ceph/keyring
>     SecretRef:     &{cinder-standard-iops-cephx-secret }
>     ReadOnly:      false
> Events:            <none>

here's the secret 
```
Name:         cinder-standard-iops-cephx-secret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
key:  41 bytes
```
**What you expected to happen**:
the deployment are expected run successfully,however it failed at this step
![image](https://user-images.githubusercontent.com/11768607/43570026-e4783b62-966b-11e8-92f6-692676749cd1.png)
and here's the more detail kubernetes log
Aug 01 21:08:50 master2 kubelet[2490]: I0801 21:08:50.540947    2490 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-ea7ba804-955b-11e8-99c3-0050568860dd" (UniqueName: "kubernetes.io/rbd/[192.168.4.181:6789 192.168.4.182:6789 192.168.4.183:6789]:volume-98adc6e3-c108-4f62-9cb3-91aebab2094d") pod "mysql-sonar-7f75f65b64-sv5pn" (UID: "5643209b-95f0-11e8-905f-005056885e00")
Aug 01 21:08:50 master2 kubelet[2490]: I0801 21:08:50.546307    2490 operation_generator.go:1121] Controller attach succeeded for volume "pvc-ea7ba804-955b-11e8-99c3-0050568860dd" (UniqueName: "kubernetes.io/rbd/[192.168.4.181:6789 192.168.4.182:6789 192.168.4.183:6789]:volume-98adc6e3-c108-4f62-9cb3-91aebab2094d") pod "mysql-sonar-7f75f65b64-sv5pn" (UID: "5643209b-95f0-11e8-905f-005056885e00") device path: ""
Aug 01 21:08:50 master2 kubelet[2490]: I0801 21:08:50.647216    2490 reconciler.go:262] operationExecutor.MountVolume started for volume "pvc-ea7ba804-955b-11e8-99c3-0050568860dd" (UniqueName: "kubernetes.io/rbd/[192.168.4.181:6789 192.168.4.182:6789 192.168.4.183:6789]:volume-98adc6e3-c108-4f62-9cb3-91aebab2094d") pod "mysql-sonar-7f75f65b64-sv5pn" (UID: "5643209b-95f0-11e8-905f-005056885e00")
Aug 01 21:08:50 master2 kubelet[2490]: I0801 21:08:50.647296    2490 operation_generator.go:447] MountVolume.WaitForAttach entering for volume "pvc-ea7ba804-955b-11e8-99c3-0050568860dd" (UniqueName: "kubernetes.io/rbd/[192.168.4.181:6789 192.168.4.182:6789 192.168.4.183:6789]:volume-98adc6e3-c108-4f62-9cb3-91aebab2094d") pod "mysql-sonar-7f75f65b64-sv5pn" (UID: "5643209b-95f0-11e8-905f-005056885e00") DevicePath ""
Aug 01 21:08:51 master2 kubelet[2490]: E0801 21:08:51.367069    2490 kubelet.go:1630] Unable to mount volumes for pod "mysql-sonar-7f75f65b64-sv5pn_default(5643209b-95f0-11e8-905f-005056885e00)": timeout expired waiting for volumes to attach/mount for pod "default"/"mysql-sonar-7f75f65b64-sv5pn". list of unattached/unmounted volumes=[mysql-sonar]; skipping pod
Aug 01 21:08:51 master2 kubelet[2490]: E0801 21:08:51.367159    2490 pod_workers.go:186] Error syncing pod 5643209b-95f0-11e8-905f-005056885e00 ("mysql-sonar-7f75f65b64-sv5pn_default(5643209b-95f0-11e8-905f-005056885e00)"), skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"mysql-sonar-7f75f65b64-sv5pn". list of unattached/unmounted volumes=[mysql-sonar]

Any help will be appreciated very much

**Comment by jianglingxia** [comment]
the log maybe mean that your disk not attached the minion, is the scenero that your backend storage is rbd driver? show your storageclass and the backend volume type ,thanks!

**Comment by npu21** [comment]
sure，here's the storageclass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: cinder-standard-iops
provisioner: openstack.org/standalone-cinder
parameters:
  type: standard-iops
```
and the backend storage is rbd,the response from cinder api like this

```
{
    "volume": {
        "migration_status": null,
        "attachments": [
            {
                "server_id": null,
                "attachment_id": "e5ab5c91-c8f2-45f0-a0b6-3a7bd50cd38e",
                "attached_at": "2018-08-01T07:24:49.000000",
                "host_name": "standalone-cinder.k8s.io",
                "volume_id": "98adc6e3-c108-4f62-9cb3-91aebab2094d",
                "device": "/k8s.io/standalone-cinder",
                "id": "98adc6e3-c108-4f62-9cb3-91aebab2094d"
            }
        ],
        "links": [
            {
                "href": "https://10.110.25.130:8776/v2/c834457fa4a54b5ebc34c310503eee4d/volumes/98adc6e3-c108-4f62-9cb3-91aebab2094d",
                "rel": "self"
            },
            {
                "href": "https://10.110.25.130:8776/c834457fa4a54b5ebc34c310503eee4d/volumes/98adc6e3-c108-4f62-9cb3-91aebab2094d",
                "rel": "bookmark"
            }
        ],
        "availability_zone": "nova",
        "os-vol-host-attr:host": "ceph@ceph#ceph",
        "encrypted": false,
        "updated_at": "2018-08-01T07:24:49.000000",
        "replication_status": null,
        "snapshot_id": null,
        "id": "98adc6e3-c108-4f62-9cb3-91aebab2094d",
        "size": 1,
        "user_id": "255e15ab28b54937adba5757e00cbd83",
        "os-vol-tenant-attr:tenant_id": "c834457fa4a54b5ebc34c310503eee4d",
        "os-vol-mig-status-attr:migstat": null,
        "metadata": {
            "attached_mode": "rw"
        },
        "status": "in-use",
        "description": null,
        "multiattach": false,
        "source_volid": null,
        "consistencygroup_id": null,
        "os-vol-mig-status-attr:name_id": null,
        "name": "cinder-dynamic-pvc-ea8ab60a-955b-11e8-b36c-eeeeeeeeeeee",
        "bootable": "false",
        "created_at": "2018-08-01T07:24:30.000000",
        "volume_type": "standard-iops"
    }
}
```
