### ISSUE TITLE
Error processing "csi-xxxxx-xxxxxxxxx-xxxxxx": failed to attach: rpc error: code = Internal desc = [ControllerPublishVolume] failed to attach volume: Volume "xxxxx-xxxxxxxxx-xxxxxx" failed to be attached within the alloted time

### ISSUE THREAD

**Issue by asow25** [kubernetes/cloud-provider-openstack#2558]
Hi, I need help? I deployed **openstack-cinder-csi** helm chart to use CSI Cinder, and after a while of use, volumes are created in openstack, on 03 volumes but it failed to attach to workers 1 or 2:
```
Failed to WaitDiskAttached: Volume "xxxxx-xxxxxxxxx-xxxxxx" failed to be attached within the allotted time GRPC error: rpc error: code = Internal desc = [ControllerPublishVolume] failed to attach volume: Volume "xxxxx-xxxxxxxxx-xxxxxxx-xxxxxx" failed to be attached within the allotted time
```
I have restarted all objects
```
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/openstack-cinder-csi-controllerplugin-869985cbc5-54qz4   6/6     Running   0          77m
pod/openstack-cinder-csi-nodeplugin-7k5rf                    3/3     Running   0          75m
pod/openstack-cinder-csi-nodeplugin-lvsjw                    3/3     Running   0          78m
pod/openstack-cinder-csi-nodeplugin-m2rcq                    3/3     Running   0          75m
pod/openstack-cinder-csi-nodeplugin-mcg24                    3/3     Running   0          78m
pod/openstack-cinder-csi-nodeplugin-wp82d                    3/3     Running   0          77m
pod/openstack-cinder-csi-nodeplugin-z57n2                    3/3     Running   0          76m

```

but before that, I noticed:

```
csi-attach:
Restart Count: 1
Last State: Terminated with an exit code of 255 (Error).
Started: Thu, 22 Feb 2024 11:16:34 +0000
Reason for Restart: The container terminated with an error.

csi-provisioner:
Restart Count: 2
Last State: Terminated with an exit code of 1 (Lost connection to CSI driver, exiting).
Started: Thu, 22 Feb 2024 12:24:42 +0000
Reason for Restart: Lost connection to CSI driver.

csi-snapshotter:
Restart Count: 0
The container is running without any restarts.

csi-resizer:
Restart Count: 2
Last State: Terminated with an exit code of 255 (Error).
Started: Thu, 22 Feb 2024 11:35:58 +0000
Reason for Restart: The container terminated with an error.

liveness-probe:
Restart Count: 0
The container is running without any restarts.

cinder-csi-plugin:
Restart Count: 0
The container is running without any restarts.
```

**Comment by Nils98Ar** [comment]
@SowAbdoul Do you remember the solution?

**Comment by rarg27** [comment]
+1

**Comment by Nils98Ar** [comment]
In our case the problem was that we attach the disks via virtio-blk/pci in libvirt which leads to a limit of 25 disks (maybe 26, not quite sure) per OpenStack instance.

As a first step I have added the following snippet to the cloud config to make cinder-csi / K8s aware of the limit. Now kube-scheduler seems to take the node-volume-attach-limit into account when scheduling a pod with a cinder volume at least:
```
[BlockStorage]
  node-volume-attach-limit="25"
```

The next step would probably be switching from virtio-blk/pci to virtio-scsi which should support thousands of disks per instance. You would configure this by adding the following properties to your node image:
```
--property hw_disk_bus=scsi --property hw_scsi_model=virtio-scsi
```

**Comment by Nils98Ar** [comment]
I am still looking why the `csi-*` containers are restarting but it seems that it is not related with the `failed to be attached within the allotted time` error in our case.

**Comment by abdoul-sow** [comment]
Hello @Nils98Ar My apologies for the delay. Here you go, this is what I use.
```
# Openstack variables
openstack_auth_region="africa-west1"
openstack_auth_url=https://localhost:5000
openstack_application_credential_id="xxxxxxxx"
openstack_application_credential_secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


openstack-cinder-csi.yml
---
- name: Install Container Storage Interface for Openstack Cinder
  kubernetes.core.helm:
    kubeconfig: /etc/kubernetes/admin.conf
    chart_ref: openstack-cinder-csi
    chart_repo_url: https://kubernetes.github.io/cloud-provider-openstack/
    chart_version: "2.29.0-alpha.4"
    create_namespace: true
    release_name: openstack-cinder-csi
    release_namespace: openstack-cinder-csi
    release_state: present
    release_values:
      fullnameOverride: openstack-cinder-csi
      secret:
        enabled: true
        hostMount: false
        create: true
        name: openstack-cinder-csi-cloud-config
        data:
          cloud.conf: |-
            [Global]
            region={{ openstack_auth_region }}
            auth-url={{ openstack_auth_url }}
            os-endpoint-type={{ openstack_endpoint_type | default('public') }}
            application-credential-id={{ openstack_application_credential_id }}
            application-credential-secret={{ openstack_application_credential_secret }}
      storageClass:
        enabled: true
        custom: |-
          ---
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: cinder
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
          provisioner: cinder.csi.openstack.org
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
      clusterID: "{{ kubernetes_cluster_name }}"

```
