### ISSUE TITLE
cinder-csi-plugin@1.31.1: `--cloud-name` should not be required when running without credentials (`--node-service-no-os-client=true`)

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/cloud-provider-openstack#2677]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We are running the cinder-csi-driver without credentials (with the `--node-service-no-os-client=true` flag). However, starting v1.31.1, the cinder-csi-driver requires `--cloud-name` to be specified. 

cinder-csi-plugin@v1.31.1 node service fails with:
```
W0927 10:56:05.818771      10 main.go:113] Failed to GetOpenStackProvider : GetConfigFromFiles cloud name "" not found in configuration files: [/etc/kubernetes/cloudprovider/cloudprovider.conf]
```

cinder-csi-plugin args:
```yaml
  containers:
  - name: csi-driver
    image: registry.k8s.io/provider-os/cinder-csi-plugin:v1.31.1
    args:
    - /bin/cinder-csi-plugin
    - --endpoint=$(CSI_ENDPOINT)
    - --nodeid=$(NODE_ID)
    - --cloud-config=/etc/kubernetes/cloudprovider/cloudprovider.conf
    - --user-agent=foo
    - --user-agent=bar
    - --user-agent=baz
    - --v=2
    - --vmodule=mount*=4,nodeserver=3,utils=2,driver=4,openstack=4,client=4,server=4,controllerserver=4
    - --node-service-no-os-client=true
    - --provide-controller-service=false
```

cinder-csi-plugin config:
```
[BlockStorage]
rescan-on-resize=true
node-volume-attach-limit=5
```

The corresponding changes are:
- https://github.com/kubernetes/cloud-provider-openstack/pull/2551
- https://github.com/kubernetes/cloud-provider-openstack/pull/2655

**What you expected to happen**:
cinder-csi-plugin@1.31.1 to be able to run with `--node-service-no-os-client=true` without requiring  `--cloud-name` to be specified and configured.

Most likely the issue can be workarounded by specifying dummy values such as `--cloud-name foo` and empty section `[Global "foo"]`.

**How to reproduce it**:
See above.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: v1.31.1
- OpenStack version:
- Others:
