### ISSUE TITLE
[occm] LoadBalancer creation fails after service type is reverted due to stale annotations

### ISSUE THREAD

**Issue by chnyda** [kubernetes/cloud-provider-openstack#2751]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
If a service was previously of type LoadBalancer, then was switched to another type (for instance NodePort) and the service is switched again to LoadBalancer : the LoadBalancer fails to be created because the LoadBalancer cannot be found (based on the ID from the annotations).

**What you expected to happen**:
The LoadBalancer should be created without any issue

**How to reproduce it**:
- create a svc of type LoadBalancer
- wait for the LB to be ready
- switch the svc to ClusterIP or NodePort
- wait for the LB to be deleted
- switch against the svc to LoadBalancer
- It does not work because there are these annotations remaining:
```
metadata:
  annotations:
    loadbalancer.openstack.org/load-balancer-address: 185.22.97.21
    loadbalancer.openstack.org/load-balancer-id: 5b268775-d01c-487d-83c6-f77308a9500a
```

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.31.1
- OpenStack version: Zed
- Others: No
