### ISSUE TITLE
Manila CSI unnecessarily picky about openstack creds

### ISSUE THREAD

**Issue by mandre** [kubernetes/cloud-provider-openstack#2757]
While testing a Manila change on an OpenStack environment with application credentials, I got a successful install however Manila CSI was reporting issues when trying to provision a volume:

```
E1119 16:11:03.280195       1 controller.go:957] error syncing claim "e5eda1ee-29c2-4aef-bfd5-146c0da60439": failed to provision volume with StorageClass "csi-manila-ceph": rpc error: code = InvalidArgument desc = invalid OpenStack secrets: parameter 'os-userName' requires 'os-password'
```

And

```
E1119 16:12:28.492969       1 controller.go:957] error syncing claim "e5eda1ee-29c2-4aef-bfd5-146c0da60439": failed to provision volume with StorageClass "csi-manila-ceph": rpc error: code = InvalidArgument desc = invalid OpenStack secrets: parameter 'os-domainName' requires exactly one of [os-password os-clientCertPath] parameters
```

It turns out, I had unneeded attributes in my clouds.yaml that caused Manila-CSI to fail.

```
openstack:
  auth:
    application_credential_id: xxx
    application_credential_secret: xxx
    auth_url: xxx
    user_domain_name: xxx # Not necessary
    username: xxx # Not necessary
  auth_type: v3applicationcredential
  endpoint_type: public
  identity_api_version: "3"
  region_name: regionOne
```

Removing `user_domain_name` and `username` from my `clouds.yaml` allowed Manila to provision volumes.

Manila-CSI should be able to ignore these extra attributes, like the CLI openstack client does.
