### ISSUE TITLE
[OCCM] multi-region support

### ISSUE THREAD

**Issue by spnngl** [kubernetes/cloud-provider-openstack#2763]
Hi,

I'm trying to deploy kubernetes on a multi-region openstack project (2az) and have difficulties.
It seems occm can only read 1 [region](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/openstack.go#L231)/[region_name](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/client/client.go#L204) at a time and cloud is only a string (ini file).

Is it possible to config multiple clouds and/or regions for 1 occm ?

I also tried to deploy 1 occm by region but the charts use hostnetwork on a hard set port + a not configurable lease shared between them all

I have a clouds.yaml
```
clouds:
  az1:
    auth:
      auth_url: "https://auth.az1/"
      project_id: "xxx"
      project_name: "xxx"
      username: "xxx"
      password: "xxx"
      user_domain_name: "Default"
      project_domain_id: "default"
    interface: "public"
    identity_api_version: 3
    region_name: "az1"
  az2:
    auth:
      auth_url: "https://auth.az2/"
      project_id: "xxx"
      project_name: "xxx"
      username: "xxx"
      password: "xxx"
      user_domain_name: "Default"
      project_domain_id: "default"
    interface: "public"
    identity_api_version: 3
    region_name: "az2"
```

Here my cloud.conf
```
[Global]
cloud = "az1"
clouds-file = "/etc/openstack/secret/clouds.yaml"
use-clouds = "true"

[Networking]
internal-network-name = "toto"
public-network-name = "toto-ext"

[BlockStorage]
bs-version = "v3"
ignore-volume-az = "true"
```
