### ISSUE TITLE
[occm octavia] UDP listener with PROXY protocol enabled fails to be created

### ISSUE THREAD

**Issue by danfai** [kubernetes/cloud-provider-openstack#2854]
When an port with UDP is specified in the service definition and the service is configured with proxyProtocol, the pool will get PROXY as the pool type, while it should be UDP.
In case healthmonitors are configured by default octavia will complain to not be able to create a healthmonitor of type UDP-CONNECT with a pool having protocol PROXY

The corresponding lines are in https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/loadbalancer.go#L977 and 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/loadbalancer.go#L888
The comparison should make sure to exclude UDP or SCTP type pools.

reproducer spec:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.openstack.org/proxy-protocol: "true"
  name: dummy
  namespace: default
spec:
  ports:
  - name: quic
    port: 443
    protocol: UDP
    targetPort: quic
  sessionAffinity: None
  type: LoadBalancer
```
From the logs:
`[...] faultstring: "Validation failure: The UDP-CONNECT type is only supported for pools of type UDP/SCTP."`

Generated LB:
```
[...]
  "listeners": [
    {   
      "protocol": "UDP",
      [...]
      "default_pool": {
        "lb_algorithm": "ROUND_ROBIN",
        "protocol": "PROXY",
         [...]
        "healthmonitor": {
          "type": "UDP-CONNECT",
[...]
```
