### ISSUE TITLE
Wrong entrypoint in cinder-csi-plugin image

### ISSUE THREAD

**Issue by xlucas** [kubernetes/cloud-provider-openstack#306]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When trying to run cinder-csi-plugin from manifests, the following pods are in the `RunContainerError` state:
- csi-attacher-cinderplugin
- csi-nodeplugin-cinderplugin
- csi-provisioner-cinderplugin
- csi-secret-cinderplugin

Logs show the error is the same for all pods and pertains to the `cinder` container running the `cinder-csi-plugin` image:
```
container_linux.go:247: starting container process caused "exec: \"--nodeid=<hostname>\": executable file not found in $PATH"
```

**What you expected to happen**:

Pods should be in the `Running` state.

**How to reproduce it (as minimally and precisely as possible)**:

1. Replace the base64 version of cloud-config in `manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml` with your own.

2.  Run `kubectl -f apply manifests/cinder-csi-plugin`

**Anything else we need to know?**: It sounds like the image `docker.io/k8scloudprovider/cinder-csi-plugin:latest` has not been built like the others and the entrypoint is `/bin/cinder-csi-plugin` instead of `/cinder-csi-plugin` so it fails.

Changing the container args in each manifest from:
```yaml
- name: cinder
  image: docker.io/k8scloudprovider/cinder-csi-plugin:latest
  args :
    - --nodeid=$(NODE_ID)
    - --endpoint=$(CSI_ENDPOINT)
    - --cloud-config=$(CLOUD_CONFIG)
```

To:
```yaml
- name: cinder
  image: docker.io/k8scloudprovider/cinder-csi-plugin:latest
  args :
    - /bin/cinder-csi-plugin
    - --nodeid=$(NODE_ID)
    - --endpoint=$(CSI_ENDPOINT)
    - --cloud-config=$(CLOUD_CONFIG)
```

Is a workaround to this issue.

**Environment**:
- openstack-cloud-controller-manager version: 0.2.0
- OS (e.g. from /etc/os-release): Debian 9
- Kernel (e.g. `uname -a`): `Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux`
