### ISSUE TITLE
Pods not getting IP address assigned after adding --cloud-provider=external to kubelet args

### ISSUE THREAD

**Issue by nabheet** [kubernetes/cloud-provider-openstack#428]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I am not sure that this is a bug and I didn't know where to ask this as a question (maybe on StackOverFlow?). I followed the instructions at https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-controller-manager-with-kubeadm.md to set up the controller. The controller wouldn't start because of the SSL certs mount issue which I saw somewhere (I can't find the link right now. Anyways, one of the suggested solutions was to remove the ca-certs volumeMount from the container spec. After removing ca-certs from the list, the container successfully started.

Anyways, now the issue is that every time I add `--cloud-provider=external` to kubelet args, all the kube-system pods do not get IP addresses. I have added the args multiple ways: adding to /etc/sysconfig/kubelet and via the kubeadm init config file like this: 

```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: "1.13.2"
apiServer:
  certSANs:
  - "MASTER_API_URL"
  - "IP"
controlPlaneEndpoint: "MASTER_API_URL"
cloudProvider: external
networking:
  serviceSubnet: "192.168.0.0/17"
  podSubnet: "192.168.128.0/17"
apiServerExtraArgs:
  service-node-port-range: 80-32767
  enable-admission-plugins: NodeRestriction,Initializers
  feature-gates: Initializers=true
  runtime-config: admissionregistration.k8s.io/v1alpha1
controllerManagerExtraArgs:
  external-cloud-volume-plugin: openstack
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external
```

**What you expected to happen**:
I would think the kube-system pods would still have their IPs assigned and listed in 

kubectl get all -n kube-system -o wide

**How to reproduce it (as minimally and precisely as possible)**:
Follow instructions at https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-controller-manager-with-kubeadm.md

**Anything else we need to know?**:
I am not sure what other information to provide

**Environment**:
- openstack-cloud-controller-manager version: docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest
- OS (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`): Linux master001.domain 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:  kubeadm init --config=/root/kube-adm-config.yaml
- Others:
