### ISSUE TITLE
client-keystone-auth: pipe and arguments doesn't work

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/cloud-provider-openstack#476]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:

I use the `client-keystone-auth` with only arguments passed (see the following snippet):

```yaml
- name: redacted
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --domain-name=redacted
      - --keystone-url=redacted
      - --project-name=redacted
      - --user-name=redacted
      - --password=redacted
      command: ./bin/client-keystone-auth
      env: null
```

everything works as expected when using `kubectl` without a pipe otherwise I get the following error message:

```bash
Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]
```

**What you expected to happen**:

I expected that kubectl authenticate against Keystone and passes the output to the next command.

**How to reproduce it (as minimally and precisely as possible)**:

Set only arguments in the kubeconfig and run a command like:  `kubectl get po --all-namespaces | grep 'a'`

**Anything else we need to know?**:

I already found the error: This command checks if STDIN is a terminal https://github.com/kubernetes/cloud-provider-openstack/blob/master/cmd/client-keystone-auth/main.go#L166 which returns in the case of `kubectl ...` `false` but in the case of `kubectl ... | do stuff` `true`. In the next step we jump in the [openstack.AuthOptionsFromEnv()](https://github.com/kubernetes/cloud-provider-openstack/blob/master/cmd/client-keystone-auth/main.go#L167) method which ignores the arguments.

There are two possible options to tackle this problem:

1.) Implement a fallback (if env variables are not set) with the specified arguments
2.) Set the required Env Variables for the auth method and unset them afterwards

I also would expect that an argument overwrites the value of an env variable (like it's coded).

**Environment**:
- openstack-cloud-controller-manager version: 1.13.1
- OS (e.g. from /etc/os-release): darwin / linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
