### ISSUE TITLE
example cloud-controller manifests are missing RBAC rules

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#495]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: I deployed ccm using https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml However, that file is missing all of the clusterrole rbac rules. There are quite many things that needs to be added and in my opinion it is not perfect way to just give cluster-admin for ccm.

**What you expected to happen**: I except that we could have example what kind of rules is needed.

**How to reproduce it (as minimally and precisely as possible)**: Deploy example file

**Comment by zetaab** [comment]
ok, the cluster-admin permissions does not help either:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
  labels:
    k8s-addon: openstack.addons.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-addon: openstack.addons.k8s.io
  name: system:openstack
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-addon: openstack.addons.k8s.io
  name: system:openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openstack
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: openstack-cloud-provider
  labels:
    k8s-app: openstack-cloud-provider
    k8s-addon: openstack.addons.k8s.io
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: openstack-cloud-provider
  template:
    metadata:
      labels:
        name: openstack-cloud-provider
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsUser: 1001
      serviceAccountName: cloud-controller-manager
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      containers:
      - name: openstack-cloud-controller-manager
        image: jesseh/occm:latest
        args:
          - /bin/openstack-cloud-controller-manager
          - --v=2
          - --cloud-config=/etc/kubernetes/cloud.config
          - --cloud-provider=openstack
          - --use-service-account-credentials=true
          - --address=127.0.0.1
        volumeMounts:
        - mountPath: /etc/kubernetes/cloud.config
          name: cloudconfig
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/cloud.config
        name: cloudconfig

```

logs https://gist.github.com/zetaab/643ac691542c75686bb7a27b86398728
