### ISSUE TITLE
octavia-ingress-controller no longer starts with latest image k8scloudprovider/octavia-ingress-controller:latest

### ISSUE THREAD

**Issue by zdenekjanda** [kubernetes/cloud-provider-openstack#562]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
octavia-ingress-controller pod no longer starts after pulling new image k8scloudprovider/octavia-ingress-controller:latest with ID 987a41db8ada. Worse, existing clusters pulled new image randomly when pods were rescheduled to workers with no image cache and service failed.
Image with ID aad2571eb5ee works ok.

Logs from octavia-ingress-controller pod:
```
time="2019-03-22T16:35:14Z" level=info msg="creating kubernetes API client"
time="2019-03-22T16:35:14Z" level=info msg="kubernetes API client created" version=v1.13
time="2019-03-22T16:35:14Z" level=fatal msg="failed to initialize openstack client" error="Get /: unsupported protocol scheme \"\""
```
Pod status:
```
kube-system   octavia-ingress-controller-0                                                0/1     CrashLoopBackOff   12         41m
```
My configmap:
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: octavia-ingress-controller-config
  namespace: kube-system
data:
  config: |
    cluster-name: 7d987d05-637e-48a7-ada0-f8897a829243
    openstack:
      auth-url: http://10.8.0.5:5000/v3
      trust-id: fb1d513ff0274164a7c7554b0b649abe
      user-id: 233d20b2fc194fa4be20711196f9cd00
      password: <dedacted>
    octavia:
      subnet-id: 36581dfd-ceca-46d8-96e3-01bf42d24565`
```

**What you expected to happen**:
octavia-ingress-controller pod starts

**How to reproduce it (as minimally and precisely as possible)**:
Deploy latest version of octavia-ingress-controller

**Environment**:
- openstack-cloud-controller-manager version: v1.13.4
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): 4.15.0-43-generic
- Install tools: kubeadm

Also, is there any documentation on how to debug this ? I would appreciate some easy suggestion how to create a new container of octavia-ingress-controller with altered code with debug points so i can see what it does. I am friend with Go and Gophercloud, but debugging stuff running inside kubernetes is kind of new for me. Many thanks in advance - I will then dig in and debug why exactly this happened. Many thanks !

**Comment by lingxiankong** [comment]
@zdenekjanda, I tested by following https://github.com/kubernetes/cloud-provider-openstack/blob/95bd4eb40299a449e06bf34e93c4173532d82f83/docs/using-octavia-ingress-controller.md, works for me.

Could you please paste all the manifest you were using?

**Comment by zdenekjanda** [comment]
Here is serviceaccount.yaml:
```
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: octavia-ingress-controller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: octavia-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: octavia-ingress-controller
    namespace: kube-system
```
And the deployment.yaml:
```
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: octavia-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: octavia-ingress-controller
spec:
  serviceName: octavia-ingress-controller
  replicas: 1
  selector:
    matchLabels:
      k8s-app: octavia-ingress-controller
  template:
    metadata:
      labels:
        k8s-app: octavia-ingress-controller
    spec:
      serviceAccountName: octavia-ingress-controller
      tolerations:
        - effect: NoSchedule # Make sure the pod can be scheduled on master kubelet.
          operator: Exists
        - key: CriticalAddonsOnly # Mark the pod as a critical add-on for rescheduling.
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: octavia-ingress-controller
          image: docker.io/k8scloudprovider/octavia-ingress-controller:latest
          imagePullPolicy: IfNotPresent
          args:
            - /bin/octavia-ingress-controller
            - --config=/etc/config/octavia-ingress-controller-config.yaml
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubernetes-config
              readOnly: true
            - name: ingress-config
              mountPath: /etc/config
      hostNetwork: true
      volumes:
        - name: kubernetes-config
          hostPath:
            path: /etc/kubernetes
            type: Directory
        - name: ingress-config
          configMap:
            name: octavia-ingress-controller-config
            items:
              - key: config
                path: octavia-ingress-controller-config.yaml
```
I have to point out, that this worked 100% before update to the image. So there must be some breaking change introduced, which makes new version incompatible.
