### ISSUE TITLE
Octavia ingress controller is not making a loadbalancer

### ISSUE THREAD

**Issue by HelenCousins** [kubernetes/cloud-provider-openstack#584]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
I followed the instructions at:
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-octavia-ingress-controller.md

(I am running a small k8s cluster on top of Openstack, which is Queens, and has Octavia)
 The final step is "# Wait until the ingress gets an IP address", well, OK, I've been waiting a day, and no.

Openstack does not believe that any loadbalancers have been created.

I can see no errors.

**What you expected to happen**:

Ideally I would like it to produce a loadbalancer and work as an ingress controller.  Failing that I would like it to tell me what didn't work.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the page
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-octavia-ingress-controller.md

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
openstack Queens
- OS (e.g. from /etc/os-release):
Ubuntu (Xenial)
- Kernel (e.g. `uname -a`):
 4.4.0-131-generic
- Install tools:
k8s was installed with kubespray

**Comment by lingxiankong** [comment]
@HelenCousins, thanks for reporting this issue.

Could you please provide the octavia-ingress-controller log?

**Comment by HelenCousins** [comment]
@lingxiankong I would be very happy to provide logs, but I have no idea where they are (this may be a large part of my problem)

**Comment by lingxiankong** [comment]
@HelenCousins hi, sorry for the delayed response, in case you haven't solved the issue, you can get the octavia-ingress-controller log by running `kubectl -n kube-system logs <octavia-ingress-controller-pod>`

**Comment by HelenCousins** [comment]
Ah! useful. An error.
 kubectl logs -n kube-system octavia-ingress-controller-0 
time="2019-04-26T11:40:13Z" level=info msg="Using config file" file=/etc/config/octavia-ingress-controller-config.yaml
W0426 11:40:13.687666       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2019-04-26T11:40:13Z" level=fatal msg="failed to initialize openstack client" error="Authentication failed"


Well, um, 'can't authenticate to OS' is certainly an error; the config map octavia-ingress-controller-config contains my correct user name and password to openstack though, so I'm not sure how it is failing.

**Comment by lingxiankong** [comment]
@HelenCousins FYI, the configmap in my environment looks like this:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: octavia-ingress-controller-config
  namespace: kube-system
data:
  config: |
    cluster-name: devstack-k8s
    openstack:
      auth-url: ${auth_url}
      user-id: ${user_id}
      password: password
      project-id: ${project_id}
      region: RegionOne
    octavia:
      subnet-id: ${subnet_id}
      floating-network-id: ${public_net_id}
      manage-security-groups: false
```
