### ISSUE TITLE
workaround for "x509: failed to load system roots and no roots provided" issue on CoreOS

### ISSUE THREAD

**Issue by AnalogJ** [kubernetes/cloud-provider-openstack#74]
/kind bug

**What happened**:
When deploying Kubernetes on CoreOS using `kubeadm` and a config file specifying `cloud-provider: openstack` the controller-manager will consistently die with the following error (from `docker logs`):

```
error building controller context: cloud provider could not be initialized: could not init cloud provider "openstack": Post https://URL/v2.0/tokens: x509: failed to load system roots and no roots provided
```

On CoreOS the `/etc/ssl/certs` files are all symlinks to `/usr/share/ca-certificates`

When the kuberenets controller container runs it seems unable to actually read the files in that directory, and throws an error

**What you expected to happen**:
The controller manager does not throw an error and die. 

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration

# pass in the openstack configuration to Kubernetes.
cloudProvider: openstack
apiServerExtraArgs:
    cloud-provider: openstack
    cloud-config: /etc/cloud/bootstrap/cloud.conf
apiServerExtraVolumes:
- name: oscloudcfg
  hostPath: /etc/cloud/bootstrap/
  mountPath: /etc/cloud/bootstrap/

controllerManagerExtraArgs:
    cloud-provider: openstack
    cloud-config: /etc/cloud/bootstrap/cloud.conf
controllerManagerExtraVolumes:
- name: oscloudcfg
  hostPath: /etc/cloud/bootstrap/
  mountPath: /etc/cloud/bootstrap/
```

**Anything else we need to know?**:
The workaround is to add the following sections to your `kubeadm.conf` file:

```
apiServerExtraVolumes:
- name: ca-certs
  hostPath: /usr/share/ca-certificates/
  mountPath: /etc/ssl/certs/
controllerManagerExtraVolumes:
- name: ca-certs
  hostPath: /usr/share/ca-certificates/
  mountPath: /etc/ssl/certs/
```

**Environment**:
- openstack-cloud-controller-manager version: N/A
- OS (e.g. from /etc/os-release): 

```NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
```

- Kernel (e.g. `uname -a`):

Linux kubestack-controller0 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 Intel Core Processor (Haswell, no TSX) GenuineIntel GNU/Linux

- Install tools: kubeadm
- Others:

**Comment by kartoch** [comment]
The problem is some certificates in `/etc/ssl/certs/` are links to files in `/usr/share/ca-certificates/` so an alternative way to fix it is to mount both directories:

```
    volumeMounts:
[...]
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /usr/share/ca-certificates/
      name: ca-real-certs
      readOnly: true
[...]
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates/
      type: DirectoryOrCreate
    name: ca-real-certs
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
```
