### ISSUE TITLE
Failed to get Barbican client Post x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sfxworks** [kubernetes/cloud-provider-openstack#741]
/kind bug

When attempting to deploy the Barbican KMS container on the cluster while setting appropriate configurations in place, I get an error stating that the cert is invalid. However, our endpoint at  https://cloud.lax1.imhcloud.net:5000/v3/auth/tokens is not self-signed.

Likely similar to https://github.com/kubernetes/cloud-provider-openstack/issues/499 which was resolved by https://github.com/kubernetes/cloud-provider-openstack/pull/500 ?

**What you expected to happen**:
The Barbican KMS plugin to recognize that the OpenStack auth endpoint isn't self-signed and continue posting the secret.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have an endpoint that isn't self-signed
2. Setup barbican
3. Post a secret

**Environment**:
- kubeadm + daemonset from build
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: barbician-kms
  namespace: kube-system
  labels:
    component: kube-apiserver
    tier: control-plane
spec:
  selector:
    matchLabels:
      name: barbician-kms
  template:
    metadata:
      labels:
        name: barbician-kms
    spec:
      nodeSelector:
        role: master
      containers:
      - name: barbician-kms
        command: ["/bin/sh"]
        args: ["-c", "/bin/barbican-kms-plugin --socketpath /var/lib/kms/kms.sock --cloud-config /etc/kubernetes/cloud-kms.conf"]
        image: "git5.zswap.net:4567/quantomworks/barbican"
        volumeMounts:
        - name: k8s
          mountPath: /etc/kubernetes
        - name: varlibkms
          mountPath: /var/lib/kms
          mountPropagation: Bidirectional
        securityContext:
          privileged: true
      priorityClassName: system-cluster-critical
      volumes:
      - name: k8s
        hostPath:
          path: /etc/kubernetes
      - name: varlibkms
        hostPath:
          path: /var/lib/kms

```

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
```
```
Linux controller-1 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubeadm + build from https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-barbican-kms-plugin.md w/ appropriate adjustments to api server at `/etc/kubernetes/manifests/kube-apiserver.yaml`
