### ISSUE TITLE
Cinder CSI not availability zone aware

### ISSUE THREAD

**Issue by piwi91** [kubernetes/cloud-provider-openstack#765]
/kind bug

**What happened**:

When moving from in-tree `kubernetes.io/cinder` to `csi-cinderplugin`, the Cinder CSI plugin doesn't respect the availability zone of the statefulset. When `kubernetes.io/cinder` is used, this is not a problem.

**What you expected to happen**:

I would expect that the CSI Cinder plugin forces the volume and statefulset pods to be in the same availability zone.

**How to reproduce it (as minimally and precisely as possible)**:

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-archive
parameters:
  fsType: ext4
  type: archive
provisioner: csi-cinderplugin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app
spec:
  serviceName: my-app
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/www/html
          name: my-app-vol
  volumeClaimTemplates:
  - metadata:
      name: my-app-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-archive
```

**Environment**:
- openstack-cloud-controller-manager version:
`1.15.0`

- OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):
`Linux nlsvpkubew01 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools: Rancher RKE and manual Cloud Manager installation
- Others: -

**Comment by adisky** [comment]
@piwi91 please try specifying `volumeBindingMode` in storage class as 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/cinder-csi-plugin/topology/example.yaml#L6
you can also refer this doc https://kubernetes-csi.github.io/docs/topology.html

**Comment by piwi91** [comment]
@adisky Doesn't do the trick unfortunately 

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-archive
provisioner: csi-cinderplugin
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
  type: archive
```

Still the same issue
