### ISSUE TITLE
Error when mounting /var/lib/kubelet/pods in Cinder CSI Driver

### ISSUE THREAD

**Issue by alijahnas** [kubernetes/cloud-provider-openstack#772]
/kind bug

**What happened**:
When running cinder-csi-nodeplugin.yaml manifest, the container cinder-csi-plugin doesn't start and throws an error about not being able to mount /var/lib/kubelet/pods because no more space is left. The problem is that /var/lib/kubelet is already mounted and contains pods directory.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f cinder-csi-node-plugin.yaml
kubectl delete -f cinder-csi-node-plugin.yaml
kubectl apply -f cinder-csi-node-plugin.yaml

**Anything else we need to know?**:
I'll write a PR to fix this

**Environment**:
- openstack-cloud-controller-manager version: latest
- Install tools: kubectl apply

**Comment by ramineni** [comment]
@alijahnas I don't think that is the cause of error you are facing, as we are not experiencing any issue regarding the same, and also , the same manifests are being tested in CI also , which is working fine.
So, could you elaborate your error and whether it is consistent ? sharing the logs also would be good.

But ya, I agree that we could check if we need to mount both the directories or not , but that will be separate issue.

**Comment by yoichiwo7** [comment]
@ramineni 
I have experienced the same problem.
If you repeatedly create and delete the pod in the same node, number of the mount entries for `/var/lib/kubelet/pods` on the node seems to increase exponentially as following: 

```
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
    181     880   68687
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
    240    1198   85183
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
    336    1818  110615
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
    528    3346  163783
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
    912    7554  279335
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
   1680   20578  547303
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
   3216   65058 1230695
~~~~~~~
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
  12432  848034 9459815
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
  24720 3268258 31442023
gke-my-cluster-default-pool-11bd9c4a-twmb ~ # findmnt | wc
  49296 12827298 113155175
```

It looks like the mount entries becomes nested when the pod is created and the created mount entries won't be cleaned up even when the pod is deleted. It's just look like mount entries leak. When the number of the mount entries becomes too large, pod creation fails with error. To recover from this problem, you have to cleanup the mount entries by rebooting the node.

On our private cloud, I got `no space left on device` error as following:

```
Warning  Failed     7m32s                   kubelet, XXXXX  Error: failed to start container "cinder": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods\\\" to rootfs \\\"/var/lib/docker/overlay2/1c1989fa5fd09c2e321913eeb1b30f011c45841682fb1e6e988329ad31ac588d/merged\\\" at \\\"/var/lib/docker/overlay2/1c1989fa5fd09c2e321913eeb1b30f011c45841682fb1e6e988329ad31ac588d/merged/var/lib/kubelet/pods\\\" caused \\\"no space left on device\\\"\"": unknown
```

On my private GKE cluster, I got timeout error as following:

```
Warning  FailedCreatePodSandBox  28s    kubelet, XXXXX  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "pod-mount-test": operation timeout: context deadline exceeded
```

I don't know why I don't get `no space left on device` error on GKE cluster. (Perhaps the resource size of the node is larger than the nodes of our private cloud?)

But either way, this issue may cause pod creation failure in long running Kubernetes nodes. I also confirmed #773 fixed the mount entries leak mentioned above.

---

I used the following manifest to create and delete pod to reproduce the problem.

```yaml
# Pod manifest to reproduce the problem
apiVersion: v1
kind: Pod
metadata:
  name: pod-mount-test
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: test
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: kubelet
      mountPath: /var/lib/kubelet
      mountPropagation: Bidirectional
    - name: kubelet-pods
      mountPath: /var/lib/kubelet/pods
      mountPropagation: Bidirectional
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
  volumes:
  - name: kubelet
    hostPath:
        path: /var/lib/kubelet
        type: Directory
  - name: kubelet-pods
    hostPath:
        path: /var/lib/kubelet/pods
        type: Directory
```
