### ISSUE TITLE
Loss of the availability zone parameter when creating manila share

### ISSUE THREAD

**Issue by ITD27M01** [kubernetes/cloud-provider-openstack#899]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [ ] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [x] manila-csi-plugin
- [x] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
The manila-provisioner ignores zone and zones share options [1] which is intended to specify the Availability zone for shares. The Availability zone option is lost at buildCreateRequest stage [3]

**What you expected to happen**:
The manila-provisioner should pass the zone option to gophercloud as Availability Zone for the proper creation of manila share.

**How to reproduce it**:
1. The StorageClass example:
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-manila-nfs
parameters:
  type: default
  zones: zone-1
  protocol: NFS
  backend: nfs
provisioner: nfs.manila.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
2. The API-request on the OpenStack Manila API side:
```
Action: 'create', calling method: Controller.__getattribute__.<locals>.version_select, body: {"share":{"description":"provisioned-by=manila.csi.openstack.org","name":"pvc-f638e74f-bcc7-4ff7-bdc6-1a8b8ca4574e","share_proto":"NFS","share_type":"default","size":5}}
```
**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: 1.16.0
- OpenStack version: All versions
- Others:

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/a835a98c0d0e4767bfe12e2b3f1a0e0fc13a52ff/pkg/share/manila/shareoptions/shareoptions.go#L77

[2] https://github.com/gophercloud/gophercloud/blob/20a03f8500ac2f3122382b4427d7b1873afe24dc/openstack/sharedfilesystems/v2/shares/requests.go#L48

[3] https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/share/manila/share.go#L137
