### ISSUE TITLE
[cinder-csi-plugin] fsck error, mount error

### ISSUE THREAD

**Issue by yzhelezko** [kubernetes/cloud-provider-openstack#915]
> /kind bug

**The binaries affected**:

- [ ] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [ ] k8s-keystone-auth
- [ ] client-keystone-auth
- [ ] octavia-ingress-controller
- [ ] manila-csi-plugin
- [ ] manila-provisioner
- [ ] magnum-auto-healer
- [ ] barbican-kms-plugin

**What happened**:
tying to create pvc
cinder-csi-plugin logs
```
I0129 13:12:58.786740       1 mount_linux.go:287] `fsck` error fsck from util-linux 2.29.2
fsck.ext2: Bad magic number in super-block while trying to open /dev/vdc
/dev/vdc: 
The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

E0129 13:12:58.803489       1 mount_linux.go:140] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/disk/by-id/virtio-5b77f374-4351-4b8f-b /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-efbb1829-06bc-43e5-adbc-c15ffbab10e3/globalmount
Output: mount: wrong fs type, bad option, bad superblock on /dev/vdc,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

I0129 13:12:58.809304       1 mount_linux.go:322] Disk "/dev/disk/by-id/virtio-5b77f374-4351-4b8f-b" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/disk/by-id/virtio-5b77f374-4351-4b8f-b]
I0129 13:13:01.388338       1 mount_linux.go:326] Disk successfully formatted (mkfs): ext4 - /dev/disk/by-id/virtio-5b77f374-4351-4b8f-b /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-efbb1829-06bc-43e5-adbc-c15ffbab10e3/globalmount
```
pvc seems like works good
```
[core@ate-tc3w4dzt6znh-master-0 ~]$ kubectl get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
csi-pvc-cinderplugin   Bound    pvc-efbb1829-06bc-43e5-adbc-c15ffbab10e3   50Gi       RWO            standard-csi   142m
```
used nginx.yaml to test pvc , mounted to /var/lib/www/test
```
root@nginx:/var/lib/www/test# ls
ls: cannot open directory '.': Permission denied
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: v1.17.0
- OpenStack version: train
- Kubernetes v1.17.1
- Fedora CoreOS 31
- Cinder CSI Version: latest

**Comment by lingxiankong** [comment]
@yzhelezko I can't reproduce the issue.

```
$ kubectl exec nginx -it -- bash
root@nginx:/# ls -l /var/lib/www/test
total 16
drwx------ 2 root root 16384 Jan 27 21:18 lost+found
root@nginx:/# cd /var/lib/www/test
root@nginx:/var/lib/www/test# ls -l
total 16
drwx------ 2 root root 16384 Jan 27 21:18 lost+found
root@nginx:/var/lib/www/test#
```

Could you please provide your yamls?

**Comment by yzhelezko** [comment]
one thing I forget to show:
```
Events:
  Type     Reason                  Age        From                                         Message
  ----     ------                  ----       ----                                         -------
  Warning  FailedScheduling        <unknown>  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "nginx": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling        <unknown>  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "nginx": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               <unknown>  default-scheduler                            Successfully assigned default/nginx to rho-20-cluster-pbr7fr2hwegx-node-0
  Normal   SuccessfulAttachVolume  29s        attachdetach-controller                      AttachVolume.Attach succeeded for volume "pvc-d615bf6e-1d4c-4a9c-bbf7-687791228c68"
  Normal   Pulled                  14s        kubelet, rho-20-cluster-pbr7fr2hwegx-node-0  Container image "nginx" already present on machine
  Normal   Created                 14s        kubelet, rho-20-cluster-pbr7fr2hwegx-node-0  Created container nginx
  Normal   Started                 14s        kubelet, rho-20-cluster-pbr7fr2hwegx-node-0  Started container nginx
[core@rho-20-cluster-pbr7fr2hwegx-master-0 ~]$ kubectl exec nginx -it bash
root@nginx:/# ls /var/lib/www/html
ls: cannot open directory '/var/lib/www/html': Permission denied
root@nginx:/# 
```

Nginx yaml
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-csi
  annotations: 
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
parameters:
  type: RBD
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-cinderplugin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: csi-data-cinderplugin 
  volumes:
  - name: csi-data-cinderplugin
    persistentVolumeClaim:
      claimName: csi-pvc-cinderplugin
      readOnly: false
```
