### ISSUE TITLE
Octavia ingress Controller: failed to find octavia endpoint 

### ISSUE THREAD

**Issue by snehalasarode** [kubernetes/cloud-provider-openstack#980]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happens**:

I am using Octavia ingress controller for my cluster. Using the same configuration as provided in this document. when i am trying to deploy Octavia ingress controller for my cluster the pod creating goes to the CrashLookBackOff error. 

**What you expected to happen**:
Pod should be created for Octavia ingress controller and Loadbalancer should be created in openstack.

**What happened**:
Octavia ingress controller pod is Going to CrashLoopBackOff error.
when i check the logs of that pod i am getting following error:
failed to find octavia endpoint for region cn-south-1: No suitable endpoint could be found in the service catalog.

**How to reproduce it**:
```
cat <<EOF > /etc/kubernetes/octavia-ingress-controller/serviceaccount.yaml
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: octavia-ingress-controller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: octavia-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: octavia-ingress-controller
    namespace: kube-system
EOF
```
kubectl apply -f /etc/kubernetes/octavia-ingress-controller/serviceaccount.yaml
```

cat <<EOF > /etc/kubernetes/octavia-ingress-controller/config.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: octavia-ingress-controller-config
  namespace: kube-system
data:
  config: |
    cluster-name: ${cluster_name}
    openstack:
      auth-url: ${auth_url}
      domain-name: ${domain-name}
      username: ${user_id}
      password: ${password}
      project-id: ${project_id}
      region: ${region}
    octavia:
      subnet-id: ${subnet_id}
      floating-network-id: ${public_net_id}
EOF
```
kubectl apply -f /etc/kubernetes/octavia-ingress-controller/config.yaml

```
image="docker.io/k8scloudprovider/octavia-ingress-controller:latest"

cat <<EOF > /etc/kubernetes/octavia-ingress-controller/deployment.yaml
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: octavia-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: octavia-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: octavia-ingress-controller
  serviceName: octavia-ingress-controller
  template:
    metadata:
      labels:
        k8s-app: octavia-ingress-controller
    spec:
      serviceAccountName: octavia-ingress-controller
      tolerations:
        - effect: NoSchedule # Make sure the pod can be scheduled on master kubelet.
          operator: Exists
        - key: CriticalAddonsOnly # Mark the pod as a critical add-on for rescheduling.
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: octavia-ingress-controller
          image: ${image}
          imagePullPolicy: IfNotPresent
          args:
            - /bin/octavia-ingress-controller
            - --config=/etc/config/octavia-ingress-controller-config.yaml
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubernetes-config
              readOnly: true
            - name: ingress-config
              mountPath: /etc/config
      hostNetwork: true
      volumes:
        - name: kubernetes-config
          hostPath:
            path: /etc/kubernetes
            type: Directory
        - name: ingress-config
          configMap:
            name: octavia-ingress-controller-config
            items:
              - key: config
                path: octavia-ingress-controller-config.yaml
EOF
```
kubectl apply -f /etc/kubernetes/octavia-ingress-controller/deployment.yaml

Is there anything i am missing or any extra things i have to do for octavia endpoint.
