### ISSUE TITLE
The components miss a kustomization.yaml

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/cloud-provider-openstack#987]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**The binaries affected**:

- [x] openstack-cloud-controller-manager
- [x] cinder-csi-plugin
- [x] k8s-keystone-auth
- [x] client-keystone-auth
- [x] octavia-ingress-controller
- [x] manila-csi-plugin
- [x] manila-provisioner
- [x] magnum-auto-healer
- [x] barbican-kms-plugin

**What happened**:
I wanted to use the yaml files in:
* https://github.com/kubernetes/cloud-provider-openstack/tree/master/cluster/addons/rbac
* https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/controller-manager
* https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/cinder-csi-plugin

and refer them directly in a local `kustomization.yaml` file.
This does not work because the `cloud-provider-openstack` repository does not contain any kustomization file.

**What you expected to happen**:
There is a kustomization file which I could refer to in my `kustomization.yaml`

**How to reproduce it**:

```
DEMO_HOME=$(mktemp -d)
cat <<EOF >$DEMO_HOME/kustomization.yaml
resources:
- github.com/kubernetes/cloud-provider-openstack/cluster/addons/rbac/
#- github.com/kubernetes-sigs/kustomize/examples/multibases?ref=v1.0.6
EOF
kubectl apply -k $DEMO_HOME
```

**Anything else we need to know?**:

Would it be reasonable to add kustomization.yaml files?
If yes I would be happy to contribute :-)

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version:
- Others:

**Comment by chrischdi** [comment]
@ramineni would it make sense to add simple `kustomization.yaml` files to each of the manifest directories?
e.g. for the cinder csi plugin:

```yaml
 resources:
- cinder-csi-controllerplugin-rbac.yaml
- cinder-csi-controllerplugin.yaml
- cinder-csi-nodeplugin-rbac.yaml
- cinder-csi-nodeplugin.yaml
- csi-cinder-driver.yaml
- csi-secret-cinderplugin.yaml
```

If so I would be happy to open a PR for that :-)

**Comment by ramineni** [comment]
@chrischdi That would be great. Please go ahead

**Comment by baylisscg** [comment]
For anyone winding up here before a fix lands or who want to use an older version you can use something like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes/cloud-provider-openstack/raw/release-1.17/manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
  - https://github.com/kubernetes/cloud-provider-openstack/raw/release-1.17/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  - https://github.com/kubernetes/cloud-provider-openstack/raw/release-1.17/manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml
  - https://github.com/kubernetes/cloud-provider-openstack/raw/release-1.17/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  - https://github.com/kubernetes/cloud-provider-openstack/raw/release-1.17/manifests/cinder-csi-plugin/csi-cinder-driver.yaml
  - https://github.com/kubernetes/cloud-provider-openstack/raw/release-1.17/manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml
```

just replace the `release-1.17` with the appropriate tag.
